### ISSUE TITLE
Support new stage RC 1 for 4.5.3 in wazuh-ansible repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-ansible#1039]
## Description

This issue attempts to support a new stage RC 1 for 4.5.3 in the wazuh-ansible repository.

## Tasks

- [ ] ~~Ensure changelog is updated for 4.5.3 (if applicable).~~
- [ ] ~~Bump revision for branch 4.5.3 on wazuh-ansible repository.~~
- [x] Create tag v4.5.3-rc1 from branch 4.5.3 on wazuh-ansible repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-ansible/releases/tag/v4.5.3-rc1.
