### ISSUE TITLE
`apt` error while installing the Wazuh agent in Ubuntu

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-ansible#1059]
## Description

A new error has been found in the development of [this](https://github.com/wazuh/wazuh-ansible/issues/768) issue.

In a Ubuntu 22.04 system, an error has been generated while installing the Wazuh agent using the Wazuh Ansible deployment. This is not related to any Wazuh-specific version.

The error is the following:
```console
TASK [../roles/wazuh/ansible-wazuh-agent : Debian/Ubuntu | Install ca-certificates and gnupg] **********
ok: [192.168.57.202]

TASK [../roles/wazuh/ansible-wazuh-agent : Debian/Ubuntu | Install apt-transport-https and acl] ********
FAILED - RETRYING: [192.168.57.202]: Debian/Ubuntu | Install apt-transport-https and acl (3 retries left).
FAILED - RETRYING: [192.168.57.202]: Debian/Ubuntu | Install apt-transport-https and acl (2 retries left).
FAILED - RETRYING: [192.168.57.202]: Debian/Ubuntu | Install apt-transport-https and acl (1 retries left).
fatal: [192.168.57.202]: FAILED! => {"attempts": 3, "cache_update_time": 1680158383, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'apt-transport-https=2.4.8' 'acl=2.3.1-1'' failed: E: Failed to fetch https://mirrors.edge.kernel.org/ubuntu/pool/universe/a/apt/apt-transport-https_2.4.8_all.deb  404  Not Found [IP: 147.75.80.249 443]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "rc": 100, "stderr": "E: Failed to fetch https://mirrors.edge.kernel.org/ubuntu/pool/universe/a/apt/apt-transport-https_2.4.8_all.deb  404  Not Found [IP: 147.75.80.249 443]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stderr_lines": ["E: Failed to fetch https://mirrors.edge.kernel.org/ubuntu/pool/universe/a/apt/apt-transport-https_2.4.8_all.deb  404  Not Found [IP: 147.75.80.249 443]", "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following NEW packages will be installed:\n  acl apt-transport-https\n0 upgraded, 2 newly installed, 0 to remove and 3 not upgraded.\nNeed to get 1506 B/40.0 kB of archives.\nAfter this operation, 374 kB of additional disk space will be used.\nErr:1 https://mirrors.edge.kernel.org/ubuntu jammy-updates/universe amd64 apt-transport-https all 2.4.8\n  404  Not Found [IP: 147.75.80.249 443]\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following NEW packages will be installed:", "  acl apt-transport-https", "0 upgraded, 2 newly installed, 0 to remove and 3 not upgraded.", "Need to get 1506 B/40.0 kB of archives.", "After this operation, 374 kB of additional disk space will be used.", "Err:1 https://mirrors.edge.kernel.org/ubuntu jammy-updates/universe amd64 apt-transport-https all 2.4.8", "  404  Not Found [IP: 147.75.80.249 443]"]}

PLAY RECAP *********************************************************************************************
192.168.57.202             : ok=7    changed=0    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   
```

The related task is trying to install some dependencies before installing the Wazuh agent using the `apt` tool. If I access to the machine and try to install the packages manually, the same error is generated:

```console
root@ubuntu22:/home/vagrant# apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 1,506 B of archives.
After this operation, 169 kB of additional disk space will be used.
Err:1 https://mirrors.edge.kernel.org/ubuntu jammy-updates/universe amd64 apt-transport-https all 2.4.8
  404  Not Found [IP: 147.75.80.249 443]
E: Failed to fetch https://mirrors.edge.kernel.org/ubuntu/pool/universe/a/apt/apt-transport-https_2.4.8_all.deb  404  Not Found [IP: 147.75.80.249 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

## Possible solution

It seems that the error is related to non-updated repositories. After running the `apt-get update` command in the machine, one of the dependencies can be installed.

```console
root@ubuntu22:/home/vagrant# apt-get update
Hit:1 https://mirrors.edge.kernel.org/ubuntu jammy InRelease
Get:2 https://mirrors.edge.kernel.org/ubuntu jammy-updates InRelease [119 kB]
Get:3 https://mirrors.edge.kernel.org/ubuntu jammy-backports InRelease [109 kB]
Get:4 https://mirrors.edge.kernel.org/ubuntu jammy-security InRelease [110 kB]
Get:5 https://mirrors.edge.kernel.org/ubuntu jammy-updates/main amd64 Packages [1,058 kB]
Get:6 https://mirrors.edge.kernel.org/ubuntu jammy-updates/main Translation-en [233 kB]
Get:7 https://mirrors.edge.kernel.org/ubuntu jammy-updates/main amd64 c-n-f Metadata [15.6 kB]
Get:8 https://mirrors.edge.kernel.org/ubuntu jammy-updates/restricted amd64 Packages [974 kB]
...
Get:30 https://mirrors.edge.kernel.org/ubuntu jammy-security/universe Translation-en [144 kB]
Get:31 https://mirrors.edge.kernel.org/ubuntu jammy-security/universe amd64 c-n-f Metadata [16.7 kB]
Get:32 https://mirrors.edge.kernel.org/ubuntu jammy-security/multiverse amd64 Packages [36.5 kB]
Get:33 https://mirrors.edge.kernel.org/ubuntu jammy-security/multiverse Translation-en [7,060 B]
Get:34 https://mirrors.edge.kernel.org/ubuntu jammy-security/multiverse amd64 c-n-f Metadata [260 B]
Fetched 7,290 kB in 4s (1,776 kB/s) 
Reading package lists... Done
root@ubuntu22:/home/vagrant# apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 142 not upgraded.
Need to get 1,510 B of archives.
After this operation, 169 kB of additional disk space will be used.
Get:1 https://mirrors.edge.kernel.org/ubuntu jammy-updates/universe amd64 apt-transport-https all 2.4.10 [1,510 B]
Fetched 1,510 B in 0s (6,282 B/s)               
Selecting previously unselected package apt-transport-https.
(Reading database ... 75812 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_2.4.10_all.deb ...
Unpacking apt-transport-https (2.4.10) ...
Setting up apt-transport-https (2.4.10) ...
Scanning processes...                              
Scanning linux images...                           

Running kernel seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor
 (qemu) binaries on this host.

```

With this, the task does not fail:
```console
TASK [../roles/wazuh/ansible-wazuh-agent : Debian/Ubuntu | Install ca-certificates and gnupg] **********
ok: [192.168.57.202]

TASK [../roles/wazuh/ansible-wazuh-agent : Debian/Ubuntu | Install apt-transport-https and acl] ********
changed: [192.168.57.202]
```

## Tasks

:warning: This was reported while installing the Wazuh agent, but there are more `apt` related tasks that would need to run the `apt-get update` command.

- [x] Include a task in the necessary roles with the `apt-get update` command to update the `apt` repositories.
- [x] Check if the installation is successful in some Debian distributions.
- [x] Apply the fix.
