### ISSUE TITLE
Support new stage Alpha 1 for 4.7.0 in wazuh-ansible repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-ansible#1077]
## Description

This issue attempts to support a new stage Alpha 1 for 4.7.0 in the wazuh-ansible repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.0 (if applicable).
- [x] Bump revision for branch 4.7.0 on wazuh-ansible repository. https://github.com/wazuh/wazuh-ansible/pull/1079
- [x] Create tag v4.7.0-alpha1 from branch 4.7.0 on wazuh-ansible repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-ansible/releases/tag/v4.7.0-alpha1.

**Comment by juliamagan** [comment]
LGTM
