### ISSUE TITLE
Support new stage RC 2 for 4.6.0 in wazuh-ansible repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-ansible#1097]
## Description

This issue attempts to support a new stage RC 2 for 4.6.0 in the wazuh-ansible repository.

## Tasks

- [ ] Ensure changelog is updated for 4.6.0 (if applicable).
- [ ] Bump revision for branch 4.6.0 on wazuh-ansible repository.
- [ ] Create tag v4.6.0-rc2 from branch 4.6.0 on wazuh-ansible repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-ansible/releases/tag/v4.6.0-rc2.
