### ISSUE TITLE
Support new stage Alpha 1 for 4.8.0 in wazuh-ansible repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-ansible#1154]
## Description

This issue attempts to support a new stage Alpha 1 for 4.8.0 in the wazuh-ansible repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.0 (if applicable).
- [ ] Bump revision for branch 4.8.0 on wazuh-ansible repository.
- [ ] Create tag v4.8.0-alpha1 from branch 4.8.0 on wazuh-ansible repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-ansible/releases/tag/v4.8.0-alpha1.

**Comment by c-bordon** [comment]
LGTM
