### ISSUE TITLE
Post release tasks for 4.7.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-ansible#1192]
## Description

This issue attempts to track the steps necessary to complete post-release maintenance tasks for 4.7.2.
The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.7.2-into-4.8.0`.

## Tasks

- [x] ~~Merge branch `4.7.2` into branch `4.8.0`.~~ https://github.com/wazuh/wazuh-ansible/issues/1192#issuecomment-1885208948
- [x] Merge branch `4.8.0` into branch `4.8.1`. https://github.com/wazuh/wazuh-ansible/pull/1193
- [x] Merge branch `4.8.1` into branch `4.8.2`. https://github.com/wazuh/wazuh-ansible/pull/1194
- [x] Merge branch `4.8.2` into branch `master`. https://github.com/wazuh/wazuh-ansible/pull/1195
- [x] Publish GitHub release as latest.
- [x] Delete all stage pre-releases for 4.7.2 (https://github.com/wazuh/wazuh-ansible/releases).
- [x] Delete all stage tags for v4.7.2. **BE CAREFUL NOT TO DELETE DEFINITIVE TAG**. Example: v4.7.2-rc1, 4.7.2-alpha1, etc.
- [x] Delete branch `4.7.2`.

**Comment by c-bordon** [comment]
![Screenshot_20240110_134043](https://github.com/wazuh/wazuh-ansible/assets/64099752/41f81fe3-9cc9-4009-9298-93c509245565)
