### ISSUE TITLE
Support new stage Beta 3 for 4.8.0 in wazuh-ansible repository

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-ansible#1226]
## Description

This issue attempts to support a new stage Beta 3 for 4.8.0 in the wazuh-ansible repository.

## Tasks

- [x] Ensure changelog is updated for 4.8.0 (if applicable).
- [x] Bump revision for branch 4.8.0 on wazuh-ansible repository. https://github.com/wazuh/wazuh-ansible/pull/1229
- [x] Create tag v4.8.0-beta3 from branch 4.8.0 on wazuh-ansible repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-ansible/releases/tag/v4.8.0-beta3.

**Comment by vcerenu** [comment]
LGTM
