### ISSUE TITLE
Support new stage Beta 3 for 4.8.0 in wazuh-docker repository

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-ansible#1227]
## Description

This issue attempts to support a new stage Beta 3 for 4.8.0 in the wazuh-docker repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.0 (if applicable).
- [ ] Bump revision for branch 4.8.0 on wazuh-docker repository.
- [ ] Create tag v4.8.0-beta3 from branch 4.8.0 on wazuh-docker repository.
- [ ] Create and publish a pre-release:
