### ISSUE TITLE
Update Ansible installation documentation 

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-ansible#1374]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 5.0.0  | wazuh/wazuh-automation#1319 |   |

## Description

I have noticed that we do not include the Amazon Linux system in our [Ansible installation documentation](https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/guide/install-ansible.html). We should consider adding this system to our documentation, as it is neither a Debian-based system nor a CentOS/RHEL system.
![image](https://github.com/user-attachments/assets/b78ade29-0ec4-4c30-831e-1457fa177729)

## Tasks

- [x] #1375
- [ ] Check that Ansible is installed and working correctly on both systems.
- [ ] Perform the Ansible deployment running a playbook on both systems. You can test the `wazuh-single.yml` playbook for example.

> [!NOTE]
> Replace the `aio` string with the `localhost` string to perform the installation on that machine.

- [ ] Check that the Wazuh central components are working correctly (searching for warnings or errors in the logs)
- [ ] Update the [documentation](https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/guide/install-ansible.html).

**Comment by teddytpc1** [comment]
For `5.0.0` this section will be replaced by a `Pre-requisites` one, so, this will not be needed.
