### ISSUE TITLE
Incorrect directory created running the `wazuh-single.yml` playbook

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-ansible#1376]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 5.0.0  | wazuh/wazuh-automation#1319 |   |

## Description
While testing the Ansible deployment, specifically using the `wazuh-single.yml` playbook, I have noticed that a new folder with name `'{'\''changed'\'': False, '\''stat'\'': {'\''exists'\'': False}, '\''failed'\'': False}'` is created after the installation is finished:

```console
[root@ip-172-31-43-41 playbooks]# ls
 ansible.cfg
'{'\''changed'\'': False, '\''stat'\'': {'\''exists'\'': False}, '\''failed'\'': False}'
 wazuh-agent.yml
 wazuh-dashboard.yml
 wazuh-indexer.yml
 wazuh-install.sh
 wazuh-manager-oss-cluster.yml
 wazuh-manager-oss.yml
 wazuh-production-ready.yml
 wazuh-single.yml
```

> [!NOTE]
> This behavior has been observed in Debian and RPM systems, so it is not exclusive of the system.

> [!WARNING]
> This behavior has been observed installing 4.8.0 and 4.8.1 Wazuh versions.

<details><summary>Installation log</summary>

```
[root@ip-172-31-43-41 playbooks]# ansible-playbook wazuh-single.yml [WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not
match 'all'

PLAY [localhost] ****************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : include_vars] ******************************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : include_vars] ******************************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : include_vars] ******************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : include_vars] ******************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Check if certificates already exists] ******************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Create local temporary directory for certificates generation] ***
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Check that the generation tool exists] **************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Download certificates generation tool] **************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Prepare the certificates generation template file] **************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Generate the node & admin certificates in local] ****************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : RedHat/CentOS/Fedora | Add Wazuh indexer repo] *********************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Install Amazon extras] *********************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Configure vm.max_map_count] ****************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Update vm.max_map_count] *******************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : RedHat/CentOS/Fedora | Install Indexer dependencies] ***************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Install Wazuh indexer] *********************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Update cache] ******************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Install Wazuh indexer dependencies] ********************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Add apt repository signing key] ************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Import Wazuh repository GPG key] ***********************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Set permissions for Wazuh repository GPG key] **********************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Add Wazuh indexer repository] **************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Install Wazuh indexer] *********************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Remove performance analyzer plugin from Wazuh indexer] *************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Remove Opensearch configuration file] ******************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Copy Opensearch Configuration File] ********************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : include_tasks] *****************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Configure Wazuh indexer JVM memmory.] ******************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Ensure extra time for Wazuh indexer to start on reboots] ***********************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Index files to remove] *********************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Remove Index Files] ************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Ensure Wazuh indexer started and enabled] **************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Wait for Wazuh indexer API] ****************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Wait for Wazuh indexer API (Private IP)] ***************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : RedHat/CentOS/Fedora | Remove Wazuh indexer repository (and clean up left-over metadata)] ***
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Reload systemd configuration] **************************************************
skipping: [localhost]

PLAY [localhost] ****************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : include_vars] ******************************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : include_vars] ******************************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : include_vars] ******************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : include_vars] ******************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Check if certificates already exists] ******************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Create local temporary directory for certificates generation] ***
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Check that the generation tool exists] **************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Download certificates generation tool] **************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Prepare the certificates generation template file] **************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Local action | Generate the node & admin certificates in local] ****************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : RedHat/CentOS/Fedora | Add Wazuh indexer repo] *********************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Install Amazon extras] *********************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Configure vm.max_map_count] ****************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Update vm.max_map_count] *******************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : RedHat/CentOS/Fedora | Install Indexer dependencies] ***************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Install Wazuh indexer] *********************************************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Update cache] ******************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Install Wazuh indexer dependencies] ********************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Add apt repository signing key] ************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Import Wazuh repository GPG key] ***********************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Set permissions for Wazuh repository GPG key] **********************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Add Wazuh indexer repository] **************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Install Wazuh indexer] *********************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Remove performance analyzer plugin from Wazuh indexer] *************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Remove Opensearch configuration file] ******************************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Copy Opensearch Configuration File] ********************************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : include_tasks] *****************************************************************
included: /home/ec2-user/wazuh-ansible/roles/wazuh/wazuh-indexer/tasks/security_actions.yml for localhost

TASK [../roles/wazuh/wazuh-indexer : Configure IP (Private address)] ************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Configure IP (Public address)] *************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Ensure Indexer certificates directory permissions.] ****************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Copy the node & admin certificates to Wazuh indexer cluster] *******************
changed: [localhost] => (item=root-ca.pem)
changed: [localhost] => (item=root-ca.key)
changed: [localhost] => (item=node-1-key.pem)
changed: [localhost] => (item=node-1.pem)
changed: [localhost] => (item=admin-key.pem)
changed: [localhost] => (item=admin.pem)

TASK [../roles/wazuh/wazuh-indexer : Restart Wazuh indexer with security configuration] *****************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Copy the Opensearch security internal users template] **************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Hashing the custom admin password] *********************************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Set the Admin user password] ***************************************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Hash the kibanaserver role/user pasword] ***************************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Set the kibanaserver user password] ********************************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Initialize the Opensearch security index in Wazuh indexer] *********************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Create custom user] ************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Configure Wazuh indexer JVM memmory.] ******************************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Ensure extra time for Wazuh indexer to start on reboots] ***********************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Index files to remove] *********************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Remove Index Files] ************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Ensure Wazuh indexer started and enabled] **************************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Wait for Wazuh indexer API] ****************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Wait for Wazuh indexer API (Private IP)] ***************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-indexer : RedHat/CentOS/Fedora | Remove Wazuh indexer repository (and clean up left-over metadata)] ***
ok: [localhost]

TASK [../roles/wazuh/wazuh-indexer : Reload systemd configuration] **************************************************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Install dependencies] **************************************************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : include_vars] **********************************************************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : include_vars] **********************************************************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : include_vars] **********************************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : include_vars] **********************************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Overlay wazuh_manager_config on top of defaults] ***********************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : include_tasks] *********************************************************
included: /home/ec2-user/wazuh-ansible/roles/wazuh/ansible-wazuh-manager/tasks/RedHat.yml for localhost

TASK [../roles/wazuh/ansible-wazuh-manager : RedHat/CentOS 5 | Install Wazuh repo] **********************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : RedHat/CentOS/Fedora | Install Wazuh repo] *****************************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : RedHat/CentOS/Fedora | Install openscap] *******************************
ok: [localhost] => (item=openscap-scanner)

TASK [../roles/wazuh/ansible-wazuh-manager : CentOS 6 | Install Software Collections (SCL) Repository] **************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : RedHat 6 | Enabling Red Hat Software Collections (RHSCL)] **************
skipping: [localhost] => (item=rhui-REGION-rhel-server-rhscl) 
skipping: [localhost] => (item=rhel-server-rhscl-6-rpms) 
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : CentOS/RedHat 6 | Install Python 2.7] **********************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : RedHat/CentOS/Fedora | Install OpenJDK 1.8] ****************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Set Distribution CIS filename for RHEL5/CentOS-5] **********************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Set Distribution CIS filename for RHEL6/CentOS-6] **********************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Set Distribution CIS filename for RHEL7/CentOS-7] **********************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Set Distribution CIS filename for RHEL7/CentOS-7 (Amazon)] *************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : CentOS/RedHat/Amazon | Install wazuh-manager] **************************
changed: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : include_tasks] *********************************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : CentOS/RedHat 6 | Enabling python2.7 and sqlite3] **********************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Install expect (EL5)] **************************************************
skipping: [localhost] => (item=expect) 
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : include_tasks] *********************************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Generate the wazuh-keystore (username)] ********************************
changed: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Generate the wazuh-keystore (password)] ********************************
changed: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Install expect] ********************************************************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Generate SSL files for authd] ******************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Copy CA, SSL key and cert for authd] ***********************************
skipping: [localhost] => (item=) 
skipping: [localhost] => (item=sslmanager.cert) 
skipping: [localhost] => (item=sslmanager.key) 
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Verifying for old init authd service] **********************************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Verifying for old systemd authd service] *******************************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Ensure ossec-authd service is disabled] ********************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Removing old init authd services] **************************************
skipping: [localhost] => (item=/etc/init.d/ossec-authd) 
skipping: [localhost] => (item=/lib/systemd/system/ossec-authd.service) 
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Installing the local_rules.xml (default local_rules.xml)] **************
changed: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Adding local rules files] **********************************************
changed: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Installing the local_decoder.xml] **************************************
changed: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Adding local decoders files] *******************************************
changed: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Configure the shared-agent.conf] ***************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Installing the local_internal_options.conf] ****************************
changed: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Retrieving Agentless Credentials] **************************************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Retrieving authd Credentials] ******************************************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Check if syslog output is enabled] *************************************
skipping: [localhost] => (item={'server': None, 'port': None, 'format': None}) 
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Check if client-syslog is enabled] *************************************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Enable client-syslog] **************************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Check if ossec-agentlessd is enabled] **********************************
ok: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Enable ossec-agentlessd] ***********************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Checking alert log output settings] ************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Configure ossec.conf] **************************************************
changed: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Ossec-authd password] **************************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Copy create_user script] ***********************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Create admin.json] *****************************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Execute create_user script] ********************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Agentless Hosts & Passwd] **********************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Encode the secret] *****************************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Ensure Wazuh Manager service is started and enabled.] ******************
changed: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Create agent groups] ***************************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : Run uninstall tasks] ***************************************************
included: /home/ec2-user/wazuh-ansible/roles/wazuh/ansible-wazuh-manager/tasks/uninstall.yml for localhost

TASK [../roles/wazuh/ansible-wazuh-manager : Debian/Ubuntu | Remove Wazuh repository.] ******************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-wazuh-manager : RedHat/CentOS/Fedora | Remove Wazuh repository (and clean up left-over metadata)] ***
ok: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : include_vars] ***********************************************************
ok: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : include_vars] ***********************************************************
ok: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : include_vars] ***********************************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : include_tasks] **********************************************************
included: /home/ec2-user/wazuh-ansible/roles/wazuh/ansible-filebeat-oss/tasks/RedHat.yml for localhost

TASK [../roles/wazuh/ansible-filebeat-oss : RedHat/CentOS/Fedora/Amazon Linux | Install Filebeats repo] *************
ok: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : include_tasks] **********************************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : Install Filebeat | Redhat] **********************************************
changed: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : Install Filebeat | Debian] **********************************************
skipping: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : Checking if Filebeat Module folder file exists] *************************
ok: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : Download Filebeat module package] ***************************************
changed: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : Unpack Filebeat module package] *****************************************
changed: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : Setting 0755 permission for Filebeat module folder] *********************
changed: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : Checking if Filebeat Module package file exists] ************************
ok: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : Delete Filebeat module package file] ************************************
changed: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : Copy Filebeat configuration.] *******************************************
changed: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : Fetch latest Wazuh alerts template] *************************************
changed: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : include_tasks] **********************************************************
included: /home/ec2-user/wazuh-ansible/roles/wazuh/ansible-filebeat-oss/tasks/security_actions.yml for localhost

TASK [../roles/wazuh/ansible-filebeat-oss : Ensure Filebeat SSL key pair directory exists.] *************************
ok: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : Copy the certificates from local to the Manager instance] ***************
changed: [localhost] => (item=node-1-key.pem)
changed: [localhost] => (item=node-1.pem)
changed: [localhost] => (item=root-ca.pem)

TASK [../roles/wazuh/ansible-filebeat-oss : Ensure Filebeat is started and enabled at boot.] ************************
changed: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : include_tasks] **********************************************************
included: /home/ec2-user/wazuh-ansible/roles/wazuh/ansible-filebeat-oss/tasks/RMRedHat.yml for localhost

TASK [../roles/wazuh/ansible-filebeat-oss : RedHat/CentOS/Fedora | Remove Filebeat repository (and clean up left-over metadata)] ***
ok: [localhost]

TASK [../roles/wazuh/ansible-filebeat-oss : include_tasks] **********************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : include_vars] ****************************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : include_vars] ****************************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : include_vars] ****************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : include_vars] ****************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : RedHat/CentOS/Fedora | Add Wazuh dashboard repo] *****************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Install Wazuh dashboard] *****************************************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : include_vars] ****************************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Download apt repository signing key] *****************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Import Wazuh repository GPG key] *********************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Set permissions for Wazuh repository GPG key] ********************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Debian systems | Add Wazuh dashboard repo] ***********************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Install Wazuh dashboard] *****************************************************
skipping: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Remove Dashboard configuration file] *****************************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Ensure Dashboard certificates directory permissions.] ************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Copy the certificates from local to the Wazuh dashboard instance] ************
changed: [localhost] => (item=root-ca.pem)
changed: [localhost] => (item=node-1-key.pem)
changed: [localhost] => (item=node-1.pem)

TASK [../roles/wazuh/wazuh-dashboard : Copy Configuration File] *****************************************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Ensuring Wazuh dashboard directory owner] ************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Wait for Wazuh-Indexer port] *************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Select correct API protocol] *************************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Attempting to delete legacy Wazuh index if exists] ***************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Create Wazuh Plugin config directory] ****************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Configure Wazuh Dashboard Plugin] ********************************************
ok: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Configure opensearch.password in opensearch_dashboards.keystore] *************
changed: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Ensure Wazuh dashboard started and enabled] **********************************
changed: [localhost]

TASK [../roles/wazuh/wazuh-dashboard : Remove Wazuh dashboard repository (and clean up left-over metadata)] *********
ok: [localhost]

RUNNING HANDLER [../roles/wazuh/wazuh-indexer : restart wazuh-indexer] **********************************************
changed: [localhost]

RUNNING HANDLER [../roles/wazuh/ansible-wazuh-manager : restart wazuh-manager] **************************************
changed: [localhost]

RUNNING HANDLER [../roles/wazuh/ansible-filebeat-oss : restart filebeat] ********************************************
changed: [localhost]

RUNNING HANDLER [../roles/wazuh/wazuh-dashboard : restart wazuh-dashboard] ******************************************
changed: [localhost]

PLAY RECAP **********************************************************************************************************
localhost                  : ok=103  changed=51   unreachable=0    failed=0    skipped=93   rescued=0    ignored=0   

[root@ip-172-31-43-41 playbooks]# rm -rf indexer/
[root@ip-172-31-43-41 playbooks]# ls
 ansible.cfg
'{'\''changed'\'': False, '\''stat'\'': {'\''exists'\'': False}, '\''failed'\'': False}'
 wazuh-agent.yml
 wazuh-dashboard.yml
 wazuh-indexer.yml
 wazuh-install.sh
 wazuh-manager-oss-cluster.yml
 wazuh-manager-oss.yml
 wazuh-production-ready.yml
 wazuh-single.yml
```
</details>

## Tasks

- [x] Investigate which task is creating that folder.
- [x] Fix or delete the related task.
- [x] Check that the folder is not created anymore after the fix.

**Comment by YisDav** [comment]
### Bug description

Ansible was found to be incorrectly generating the directory `'{'\'\'changed'\': False, 'stat': { '\''exists': False}, '\''failed'\': False}'` . So, the failure was found in the file `roles/wazuh/ansible-filebeat-oss/tasks/main.yml` Specifically, the task called `Setting 0755 permission for Filebeat module folder`.

---

**Verbose log of the execution:**

![image](https://github.com/user-attachments/assets/b7d34818-8d44-44ec-bd34-4c5106debb93)

**Comment by YisDav** [comment]
### Execution test

After the error that caused the incorrect generation of the above mentioned directory was corrected, tests were performed to prove that the directory was no longer being generated.

---

**Execution results:**

![image](https://github.com/user-attachments/assets/84dd908a-4683-4c15-b08e-1eab143aad6b)

---

**Task execution:**

![image](https://github.com/user-attachments/assets/0b9655fc-5354-44ab-8a56-bf2378fb98c3)
