### ISSUE TITLE
Support new stage RC 1 for 4.9.2 in wazuh-ansible repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-ansible#1447]
## Description

This issue attempts to support a new stage RC 1 for 4.9.2 in the wazuh-ansible repository.

## Tasks

- [ ] ~~Delete previous RC 1 release: https://github.com/wazuh/wazuh-ansible/releases/tag/v4.9.2-rc1.~~
- [ ] ~~Delete previous v4.9.2-rc1 tag.~~
- [x] Ensure changelog is updated for 4.9.2 (if applicable).
- [x] Bump revision for branch 4.9.2 on wazuh-ansible repository.
- [x] Create tag v4.9.2-rc1 from branch 4.9.2 on wazuh-ansible repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-ansible/releases/tag/v4.9.2-rc1.
