### ISSUE TITLE
Support new stage Alpha 3 for 4.10.0 in wazuh-ansible repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-ansible#1458]
## Description

This issue attempts to support a new stage Alpha 3 for 4.10.0 in the wazuh-ansible repository.

## Tasks

- [x] Ensure changelog is updated for 4.10.0 (if applicable).
- [x] Bump revision for branch 4.10.0 on wazuh-ansible repository.
- [x] Create tag v4.10.0-alpha3 from branch 4.10.0 on wazuh-ansible repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-ansible/releases/tag/v4.10.0-alpha3.

**Comment by CarlosALgit** [comment]
LGTM
