### ISSUE TITLE
SPIKE - Wazuh Ansible

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-ansible#1461]
|Objective|
|---|
| https://github.com/wazuh/internal-devel-requests/issues/1319 |

## Description
As part of the [DevOps overhaul](https://github.com/wazuh/internal-devel-requests/issues/1319) objective we need to conduct research, analyze alternatives, and design how to implement the following changes.
1. Installation process:
  - The Wazuh Ansible deployment alternative must use the Wazuh package URL instead of repositories.
  - For the development packages, the download method will be defined [here](https://github.com/wazuh/internal-devel-requests/issues/1725).
2. Installation configuration:
  - Ensure the Wazuh Ansible deployment uses out-of-the-box Wazuh configurations.
3. Testing Improvements:
  - Enhance deployment tests with additional checks, including log validation for errors and warnings.
  - Ensure tests are compatible with both production and development packages.
4. Documentation Updates:
  - Simplify Ansible installation documentation.
  - Focus on prerequisites for Wazuh Ansible deployment, using the Wazuh Kubernetes documentation as a reference.

## Implementation restrictions
- Testing Environment:
  - Tests must be implemented using GitHub Actions (GHA).
- Compatibility:
  - Ensure compatibility with both production and development package environments.
- Logs Validation:
  - Include robust log analysis to detect and report errors or warnings clearly.
- Minimal Maintenance:
  - Prioritize simplicity and minimize ongoing maintenance requirements.

## Plan
1. Research & Analysis:
  - Analyze the current Wazuh Ansible deployment process to identify required changes for using package URLs.
  - Review and integrate the development package download method outlined in [#1725](https://github.com/wazuh/internal-devel-requests/issues/1725).

2. Configuration Updates:
  - Define how to modify the Wazuh Ansible deployment to use out-of-the-box configurations.

3. Test Enhancements:
  - Define how the new GHA workflows will validate deployments with production and development packages.
  - Define how to integrate log analysis into deployment tests to identify errors and warnings.

4. Documentation Updates:
  - Define how to simplify the Ansible installation documentation.
  - Rewrite Wazuh Ansible installation documentation, focusing on prerequisites and using Wazuh Kubernetes documentation as a style guide.

**Comment by YisDav** [comment]
# Plan

A continuación, se propone un plan para la implementación y mejora del despliegue de Wazuh utilizando Ansible. Este esfuerzo forma parte de un objetivo más amplio de optimización de DevOps (DevOps Overhaul Issue Link), centrado en la adopción de configuraciones "Out-of-the-Box" (OOB) y la simplificación del proceso de instalación. 

La propuesta de este plan tiene como objetivo esbozar de forma general los pasos y consideraciones necesarias para llevar a cabo las acciones anteriormente propuestas. Este comienza con la definición de los puntos iniciales para la estructura del proyecto Ansible. Posteriormente, se considera la creación de los workflows en GitHub Actions, los cuales se alinearán con los puntos clave establecidos. Además, se desarrollará un plan para la etapa de creación del código "Out-of-the-Box" (OOB) para cada componente de Wazuh, asegurando que cada parte sea coherente con los objetivos y restricciones propuestos en este Issue. Finalmente, se abordan mejoras en la implementación de pruebas y validación de logs, así como ajustes a la documentación.

A continuación, se describen cada uno de los pasos mencionados anteriormente:

1. Definir puntos iniciales para la estructura del proyecto Ansible.
3. Crear los workflows para despliegues AIO y distribuido, alineados con los siguientes puntos clave:
4. Crear el código Out-Of-the-Box (OOB) para cada componente de Wazuh.
5. Mejorar en la implementación de test y la validación de logs, errores y advertencias.
6. Ajustes a la documentación

#

**Comment by YisDav** [comment]
# Define Starting Points for the Ansible Project Structure

Defining the overall structure of the Ansible project:
- [ ] Determine if roles will be used.
- [ ] Define the certificate generation tool (related issue here).
  - [ ] Plan according to the current setup
- [ ] Establish the general organization of the project (directories, files, etc.).

## Proposals

### Current Structure:
   - It is proposed to maintain an organization similar to the current one. This means having two main directories: one for playbooks and another for roles.
   - The playbooks directory will primarily store playbooks for Wazuh distributed and Wazuh AIO.

### Simpler Approach:
   - Other projects like CloudBox or Plone manage their roles directory similarly but keep the playbooks in the main directory.

**Comment by YisDav** [comment]
# Workflows

## Wazuh Package URL Retrieval
- [ ] [Workflows] Obtain URLs for Wazuh packages from their respective buckets
  1. **Generate the pre-signed URL**
     - Configure the role with permissions to access the package
     - Adjustments required depending on whether it is a Production, PreRelease, or Development package (either the *latest uploaded package* or packages identified with *commit-sha* in their naming).
  2. **Store the URL in a variable** that can be used later to instruct Ansible on where to download the packages.
  3. **Verify that Ansible can download the package.** Ensure the package's availability and confirm that no permission issues arise.

## Compatibility Matrix with Operating Systems

> 💡 **Note:** Support for ARM architecture will now also be included.

### Supported Operating Systems

| Name             | Version         | Architecture(s)         | Wazuh Components (supported)            |
|------------------|-----------------|-------------------------|-----------------------------------------|
| RedHat           | 8, 9            | x86_64, aarch64, arm   | Indexer, Manager, Dashboard, Agent     |
| Ubuntu           | 22.04, 24.04    | x86_64, aarch64, arm   | Indexer, Manager, Dashboard, Agent     |
| Amazon Linux     | 2, 2023         | x86_64, aarch64, arm   | Indexer, Manager, Dashboard, Agent     |
| CentOS           | 8               | x86_64, aarch64, arm   | Indexer, Manager, Dashboard, Agent     |

**Comment by YisDav** [comment]
# OOB code for each Wazuh component

## Certificate Generation
- Utilize the previously defined tool: [Learn more](https://www.notion.so/Plan-Ansible-Spike-14da752a9d3480178c58cee7c6efe3af?pvs=21)

## Create Roles/Playbooks to Deploy Each Wazuh Component

### 1. Provisioning and Installation of Wazuh Indexer
   - **Sub-steps:**
     - Download and install package(s)
       - Download and install missing dependency(ies)?
         - YUM
           - coreutils
         - APT
           - debconf
           - adduser
           - procps
     - Configure OpenSearch at `/etc/wazuh-indexer/opensearch.yml`
     - Deploy and configure certificates
     - Test installation and functionality of the component

### 2. Provisioning and Installation of Wazuh Server
   - **Sub-steps:**
     - Download and install package(s)
       - Download and install missing dependency(ies)?
         - YUM
           - coreutils
         - APT
           - debconf
           - adduser
           - procps
           - gnupg
           - apt-transport-https
     - ~~Configuration of Filebeat~~
       - ~~Filebeat configuration file at `/etc/filebeat/filebeat.yml`~~
       - ~~Store credentials in *keystore*~~
       - ~~Download alert template for Wazuh Indexer~~
       - ~~Install Wazuh module for Filebeat.~~
       - ~~Deploy and configure certificates~~
     - Configure and test connectivity with Wazuh Indexer
     - Test installation and functionality of the component

### 3. Provisioning and Installation of Wazuh Dashboard
   - **Sub-steps:**
     - Download and install package(s)
       - Download and install missing dependency(ies)?
         - YUM
           - libcap
         - APT
           - debhelper
           - tar
           - curl
           - libcap2-bin
     - Configure the dashboard
       - Configuration files:
         - `/etc/wazuh-dashboard/opensearch_dashboards.yml`
         - `/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml`
     - Deploy and configure certificates
     - ~~Enhance installation security? [Learn more](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/step-by-step.html#securing-your-wazuh-installation)~~
       - Note: This is not a production environment
     - Test installation and functionality of the component

- [ ] Create Playbook for Single Node Using Roles/Code of Each Component
- [ ] Create Playbook for Distributed Deployments Using Roles/Code of Each Component

**Comment by YisDav** [comment]
## 3. Test Improvements

### Proposals

- **Utilize Ansible Lint in PR Checks**
  
  Implement linting using the *ansible-lint* action during pull request checks to ensure code quality.
  
  [Ansible Lint GitHub Action](https://github.com/marketplace/actions/run-ansible-lint)

- **Implement Log Parsing Post-Execution**
  
  - **Log Parsing Script**
    
    Develop a script (e.g., in Python) to parse logs for specific error or warning keywords such as "ERROR", "WARNING", or custom patterns.

  - **Log Analysis System Proposal**
    
    The goal is to establish a log analysis system that facilitates review and debugging tasks, especially in case of errors or failures during any phase. This system will collect multiple logs generated by Wazuh and its components, making them available through a designated artifact.

    1. **Collection of Key Log Sources for Debugging and Diagnosis During Deployments**
       
       | Wazuh Component | Logs |
       | --- | --- |
       | Indexer | /var/log/wazuh-indexer/<br>/var/ossec/logs |
       | Manager | /var/ossec/logs/<br>/var/ossec/logs/ossec.log |
       | Dashboard | /usr/share/wazuh-dashboard/data/wazuh/logs |
       | Agent | /var/ossec/logs/<br>/var/ossec/logs/ossec.logs |

       ![Log Sources in Wazuh](https://prod-files-secure.s3.us-west-2.amazonaws.com/a1493973-e9b2-4f9b-bb0e-a6c182e4a4e9/e5172b17-707d-4e2c-99d1-ef7840acac65/image.png)
       ![Log Sources in Wazuh](https://prod-files-secure.s3.us-west-2.amazonaws.com/a1493973-e9b2-4f9b-bb0e-a6c182e4a4e9/49484012-7702-4ecb-a6a8-8226f45772ed/image.png)

    2. **Automated Log Analysis**
       
       Conduct an automated scan for errors and warnings after execution.
       
       - **Execution Type:**
         - Post-Execution: This occurs when other components have completed their deployment.

       - **Statistics Generation:**
         - A plain text file will be created containing:
           - Number of errors per component
           - Number of warnings per component
           - Total number of errors
           - Total number of warnings

    3. **Artifact Generation:**
       
       Once the statistics and logs for each component are collected, they should be uploaded as artifacts under a common directory while maintaining their full path for easy identification.

       Example structure:
       ```bash
       logs-artifact/
       ├── wazuh-manager/
       │   └── var/
       │       └── ossec/
       │           └── logs/
       │               └── ossec.log
       ├── ...
       │ 
       └── summary.txt
       ```

- **Implement Check and Diff Before Actual Deployment**
  
  Utilize the `--check` and `--diff` modes in Ansible to validate configuration changes before applying them. This is useful for verifying expected behavior without making actual modifications.

  ### **Example**
  
  ```bash
  ansible-playbook playbook.yml --check --diff

**Comment by YisDav** [comment]
# Adjustments to the Documentation

## Relocate Documentation Section
   
   It would be more convenient to have [this section](https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/guide/install-ansible.html#windows-endpoints) on the Wazuh Agent documentation page.

   - [ ] Remove [this section](https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/guide/install-ansible.html) from the documentation and replace it with a prerequisites section.

### Prerequisites
   - Ansible (core) ≥ 2.16
   - SSH
   - CentOS / RHEL 7 / Fedora
     - epel-release
   - Debian / Ubuntu
     - lsb-release
     - software-properties-common
   - Windows
     - Windows versions under current and extended support from Microsoft:
       - Ansible can manage desktop OSs including Windows 7, 8.1, and 10, and server OSs including Windows Server 2008, 2008 R2, 2012, 2012 R2, 2016, and 2019.
     - PowerShell 3.0 or newer.
     - At least .NET version 4.0 should be installed on the Windows endpoint.
     - A WinRM listener should be created and activated.

**Comment by YisDav** [comment]
### Implementation Plan

The initial implementation plan covers the following steps in a sequential manner:

1. Initial cleaning of the repository.
2. Creation of the playbook to collect information from the hosts.
3. Generation of pre-signed URLs for the necessary packages.
4. Development of the main installation playbook.
5. Creation of the validation playbook.
6. Documentation of the process.

**Comment by YisDav** [comment]
[Ansible Spike.pdf](https://github.com/user-attachments/files/18151599/Ansible.Spike.pdf)

**Comment by YisDav** [comment]
![Image](https://github.com/user-attachments/assets/284fb0a9-002c-45cb-8221-e386a05c693e)

**Comment by YisDav** [comment]
# Diagrams

![Image](https://github.com/user-attachments/assets/57cbb3c5-199c-498e-98d6-da30007acf59)

![Image](https://github.com/user-attachments/assets/b7e18bc4-0262-4909-8890-b5cf1368349d)

**Comment by YisDav** [comment]
# Update

As part of the efforts to simplify and enhance Wazuh version 5.0.0, a significant change has been introduced to the configuration of the Wazuh server. While distributed installations for this component will still be possible, communication between Wazuh servers will no longer occur. Consequently, the concepts of master and worker servers will no longer apply. Instead, all servers will function equally and will directly log relevant information to the indexer.

As a result, all distributed Wazuh deployments will now require a load balancer or proxy to distribute the workload among servers. It is still under consideration whether HAProxy or Nginx will be used for this purpose.

In this context, it will be necessary to adapt the deployment using Ansible to include the setup of this load balancer. Current discussions suggest having a dedicated host for this purpose; however, this has yet to be defined.
