### ISSUE TITLE
Support ARM architecture for Wazuh central components

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-ansible#1467]
## Description

In the Wazuh 4.10.2 version, Wazuh central components support ARM64 architecture, so it is necessary to verify that the operating systems supported by Ansible for AMD64 architecture also support ARM64.

## Tasks

- [x] Investigate the availability of supported OS for Ansible deployment for ARM architecture
- [x] Analyze what changes would be necessary to make in the playbooks to support the ARM architecture
- [x] Revise the installation documentation to include instructions and notes specific to ARM architecture setups.
- [x] Perform tests for the ARM architecture
- [x] Verify that the deployment works for both AMD64 and ARM64 architectures

## Related

[Modify installation scripts for ARM architecture.](https://github.com/wazuh/wazuh/issues/26946)

**Comment by YisDav** [comment]
# Ansible Compatibility with ARM64

Based on my research, Ansible is compatible with ARM64 architecture and supports the same operating systems as it does for AMD64, provided there is an SSH connection to the client. This means that the following operating systems are supported for ARM64 deployment:

- **CentOS 8**
- **Amazon Linux 2**
- **Ubuntu 22.04**
- **RHEL 8**

Additionally, Ansible facts can be utilized to dynamically retrieve the architecture of the target system (`ansible_architecture`), thereby facilitating seamless access to the host's architectural information. This allows us to identify whether the current host is AMD64 or ARM64. The possible values returned by the architecture fact are:

- **armv6l**: armhf
- **armv7l**: armhf
- **aarch64**: arm64
- **x86_64**: amd64
- **i386**: i386

Sources:
- [Ansible Community Documentation: Discovering variables and facts](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html)
- [Stack Overflow: Architecture fact in Ansible](https://stackoverflow.com/questions/58169348/how-is-the-architecture-fact-called-in-ansible)
- [Stack Overflow: List of Ansible pre-defined variables](https://stackoverflow.com/questions/18839509/where-can-i-get-a-list-of-ansible-pre-defined-variables)
- [Stack Overflow: Decision-making based on architecture in Ansible playbooks](https://stackoverflow.com/questions/44713880/how-do-i-make-decision-based-on-arch-in-ansible-playbooks)

**Comment by YisDav** [comment]
# Required changes

## Playbooks

- Remove unsupported parameter `"warn: false"` in the `check-packages`  [main task](https://github.com/wazuh/wazuh-ansible/blob/4.10.2/roles/wazuh/check-packages/tasks/main.yml)
- Modify the Wazuh components packages download URL in _[packages_uri.txt](https://github.com/wazuh/wazuh-ansible/blob/4.10.2/roles/wazuh/check-packages/files/packages_uri.txt)_ for  the `check-packages` task

## Workflows

- Adapt the var assignation of COMPOSITE_NAME to perform ARM64 instance allocation (i.e., Distributed & AIO PR checks)

**Comment by YisDav** [comment]
# Filebeat compatibility issue

Using the distributed Ansible workflow, a cluster of instances was launched, where the two servers (manager and worker) had ARM architecture, while the rest of the components had AMD architecture. The deployment was tested with version v4.9.2 (the latest version available in production). We also forced the use of Pre-Release for the arm64 package for Wazuh Manager.

Workflow link: [here](https://github.com/wazuh/wazuh-ansible/actions/runs/12281732374)

In this process, the following error was encountered (for both yum and apt), corresponding to no **filebeat package being found available for the arm64 architecture**.

### RHEL-based

![image](https://github.com/user-attachments/assets/dc1539e8-b37e-41c6-b53e-5a2105e27d54)

![image](https://github.com/user-attachments/assets/960cf48a-0e01-44d7-8ef9-178159c34e88)*

![image](https://github.com/user-attachments/assets/a20ba030-b28d-42cf-a1b9-1f56a6e59258)


### Debian-based

![image](https://github.com/user-attachments/assets/e8daa559-47ac-4e88-ba9e-524bd335c338)

**Comment by teddytpc1** [comment]
Packages were generated: [info](https://github.com/wazuh/internal-devel-requests/issues/1887#issuecomment-2599479706).

**Comment by YisDav** [comment]
### Update

Using the packages uploaded to the QA account, and performing a fixed setting of the repository, versioning and package download variables (among others), a functional deployment of Ansible on ARM64 hosts was achieved.

The tested hosts were: Ubuntu 22, AL2, RHEL8, CentOS 8, with an AIO installation.

### Evidence

Workflow execution link:

https://github.com/wazuh/wazuh-ansible/actions/runs/12876770897

**Comment by YisDav** [comment]
### Update

Using the packages previously uploaded, and performing a fixed setting of the repository, versioning and package download variables (among others), a functional deployment of Ansible on ARM64 hosts was achieved.

The tested hosts were: Ubuntu 22, AL2, RHEL8, CentOS 8, with an AIO installation.

### Evidence

Workflow execution link:

https://github.com/wazuh/wazuh-ansible/actions/runs/12876770897

**Comment by YisDav** [comment]
## Update

Using the packages previously uploaded, and performing a fixed setting of the repository, versioning and package download variables (among others), a functional deployment of Ansible on ARM64 hosts was achieved.

The tested hosts were: Ubuntu 22, AL2, RHEL8, CentOS 8, with an AIO and distributed installation.

### Evidence

Workflow execution links:

* AIO: https://github.com/wazuh/wazuh-ansible/actions/runs/12876770897
* Distributed: https://github.com/wazuh/wazuh-ansible/actions/runs/12887975714

### Conclusion

With minor adjustments to versions and repositories, the Wazuh Ansible installation method successfully enables the installation of Wazuh on ARM64 hosts.

Therefore, it can be concluded that the repository configuration for version 4.12.0 is fully compatible with installing Wazuh on various hosts, including both AMD64 and ARM64 architectures, across different operating systems.

**Comment by YisDav** [comment]
## Update

Using the packages previously uploaded, and performing a fixed setting of the repository, versioning and package download variables (among others), a functional deployment of Ansible on ARM64 hosts was achieved.

The tested hosts were: Ubuntu 22, AL2, RHEL8, CentOS 8, with an AIO and distributed installation.

### Evidence

Workflow execution links:

* AIO: https://github.com/wazuh/wazuh-ansible/actions/runs/12876770897
* Distributed: https://github.com/wazuh/wazuh-ansible/actions/runs/12887975714

### Conclusion

With minor adjustments ([see](https://github.com/wazuh/wazuh-ansible/commit/9d9106f813b08221c003b2008140f3cb84ca0467)) to versions and repositories, the Wazuh Ansible installation method successfully enables the installation of Wazuh on ARM64 hosts.

Therefore, it can be concluded that the repository configuration for version 4.12.0 is fully compatible with installing Wazuh on various hosts, including both AMD64 and ARM64 architectures, across different operating systems.
