### ISSUE TITLE
Update the GitHub runners image from latest to ubuntu-22.04 in Ansible workflows

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-ansible#1471]
## Description

Due to the updates that the `latest` images of GitHub runners undergo, we must set a fixed image to avoid failures in our workflows due to updates in the mentioned image.
It is recommended to define the image `ubuntu-22.04`

## Tasks

- [x] al_aio.yml
- [x] al_wazuh.yml
- [x] centos_aio.yml
- [x] centos_wazuh.yml
- [x] ubuntu_aio.yml
- [x] ubuntu_wazuh.yml

## Issue related

https://github.com/wazuh/internal-devel-requests/issues/1890

**Comment by teddytpc1** [comment]
We are going to fix the `v3` references used in `5.0.0`.
