### ISSUE TITLE
Add versioning for Wazuh Manager, Agent and Filebeat

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#197]
Hello team!

The installation task of Wazuh Manager, Agent and Filebeat don't evaluate the package version in the installation task. For example:

https://github.com/wazuh/wazuh-ansible/blob/eb66e7d4cb252b26ca4a1c9651a4154775c6e2bd/roles/wazuh/ansible-wazuh-agent/tasks/Linux.yml#L8-L14

So when executing, the last package will be installed instead of the default one (associated with tag or branch) or the desired one declared in the correspondent variable.

Adding versioning also provides the ability to upgrade packages. If explicitly set on a name, Ansible checks for version and will run the installation if differs, making upgrade process available.

### Tasks

- [x] Evaluate the implementation of `apt` and `yum` blocks

- [x] Add versioning variables and include them on installation tasks

- [x] Test upgrade version and working on different OS's (Centos, Debian...)

- [x] Update Readme and Changelog

This issue aims to give a more explicit definition of #59 stating required tasks and updates, that will be summarized here.

Best regards,

Jose

**Comment by rshad** [comment]
Hi all,

Task Update:

### Tasks

- [x] Evaluate the implementation of `apt` and `yum` blocks  `Evaluation is now done for wazuh-manager in this` [commit](https://github.com/wazuh/wazuh-ansible/commit/5d006cbc3a5300fb8c42c9efa4e8eb75f7100ca9)

- [x] Add versioning variables and include them on installation tasks `Done for wazuh-manager`

- [ ] Test upgrade version and working on different OS's (Centos, Debian...)

- [ ] Update Readme and Changelog

Proceeding with wazuh-agent and Fillebeat installations.

Kind regards,

Rshad

**Comment by rshad** [comment]
Hi all,

Task Update:

### Tasks

- [x] Evaluate the implementation of `apt` and `yum` blocks  `Evaluation is now done for wazuh-manager in this` [commit](https://github.com/wazuh/wazuh-ansible/commit/5d006cbc3a5300fb8c42c9efa4e8eb75f7100ca9)

- [x] Add versioning variables and include them on installation tasks `Done for wazuh-manager`

- [x] Test upgrade version and working on different OS's (Centos, Debian...)

- [ ] Update Readme and Changelog

Kr,

Rshad
