### ISSUE TITLE
Create Ansible playbook in order to automate the uninstallation of already installed  Wazuh components

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh-ansible#198]
Hi team!

#### Main Idea
This issue was open in order to create an Ansible playbook which uninstalls already Wazuh installed components.

####  Use Case
Imagine you create a new virtual machine and proceed to install `Wazuh` components such as:

 - Manager
 - Filebeat
 - Elasticsearch
 - ...
 
Let's say you wanted to test with a determined commit version working on issue `x` and once finished, you need to proceed to resolve a new issue `y` which imply to deal with a new different release or versión of Wazuh repo.

#### Benefits
In order to avoid such heavy task to delete the actual virtual machine and re-launch a new one, then with the requested playbook, you will only need to run it and then get the virtual machine as a clean one and prepared for new installations.

### Tasks
- [x] Implement the required roles. 
- [x] Define a playbook.
- [x] Implement the corresponding Molecule tests.
- [x] Open a PR.

Kind Regards,

Rshad Zhran

**Comment by rshad** [comment]
Hi team!

**1 step in advance! I've just created a new role for this task**

Commit: [14498420ec33a9ecb4b2ea01cac3ff49587823fb](https://github.com/wazuh/wazuh-ansible/commit/14498420ec33a9ecb4b2ea01cac3ff49587823fb).

added a new role ' /roles/wazuh/ansible-wazuh-manager-removal ' tasks for packages removal of wazuh-manager in RedHat and Debian.

Now proceeding with **Molecule** tests.

Kind Regards,

Rshad Zhran

**Comment by rshad** [comment]
Hi all,

*General Status*

### Tasks
- [x] Implement the required roles.  `Done`
- [x] Define a playbook.  `Done`
- [ ] Implement the corresponding Molecule tests. `In process`
- [ ] Open a PR. `Pending`

Kind regards,

Rshad
