### ISSUE TITLE
Add feature to use own CA when generating and distributing certificates in ES instances

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#211]
Hi team,

The current code generates own CA using Elasticsearch binaries but in some cases it's required to use a previously generated CA to sign the certificates.

In order to achieve that, some task must be performed:

##### Tasks

- [x] Refactor the certificate distribution

- [x]  Add support for PEM certificates

- [x] Adapt Ansible task to check if a CA exists 

- [x] Adapt the generation of certificates to use previously stated CA

- [x] Check the certificates are properly generated and distributed

- [x] Verify the configuration and status of the instance.

Best regards,

Jose

**Comment by jm404** [comment]
Hi team,

As this issue requires big changes, I will update about the changes and features implemented.

These changes are being pushed in https://github.com/wazuh/wazuh-ansible/tree/elk-security-dev ,  you may also notice another branches having same prefix that are related to this one.

### Certificates importing parameters

In order to propagate the certiciate generated in the *Generator node* to other Elastic instances nodes, they will be copied in the Ansible master which has access to all nodes. This way we can distribute the certs without having to implement another SSH key.

Parameters involved in this configuration and their default values are:

- `master_certs_destination: /es_certs` : Path of Ansible master where the **certs.zip** file will be copied and extracted. Exists in ES, Kibana and Filebeat roles as a default parameter.

- `elasticsearch_node_name: node-1`: Node name that will be applied to the ES instance.

- `kibana_node_name: node-1` Node name that will be applied to the Kibana instance.

- `filebeat_node_name: node-1`: Node name that will be applied to the Filebeat instance.

### Certificates propagation

The distribution is performed by copying from the Ansible master to Elastic intances defined in `instances.yml` with the

https://github.com/wazuh/wazuh-ansible/blob/9580056b747d44144391985984ab012ba38165a7/roles/elastic-stack/ansible-elasticsearch/tasks/main.yml#L184-L195

### Improvements in the distribution

Some little changes have been applied to make the installation safer and cleaner:

- Ensure unzip dependency is satisified: [#ed4b2e7](https://github.com/wazuh/wazuh-ansible/commit/ed4b2e7947f40e7745d3d057a96e1336c65724be)
- Remove the **certs.zip** after generation in the generator node: [#45356ee](https://github.com/wazuh/wazuh-ansible/commit/45356ee3ef68bd3a3d20b578d81e2df77fd26cac)
- Fix X-Pack conditionals: [#0cc4838](https://github.com/wazuh/wazuh-ansible/commit/0cc4838e1da6cbb651052481f1a15cacd5dd9fa4) & [#9580056](https://github.com/wazuh/wazuh-ansible/commit/9580056b747d44144391985984ab012ba38165a7)

Best regards

Jose

**Comment by jm404** [comment]
Hi team,

Today's changes are summarized in the following:

### Move Xpack configuration from to xpack-security.yml

In order to keep the `main.yml` file clear and readable, all the code related to the X-Pack configuration has been moved to `xpack-security.yml` file.

You can check the changes at: [#f8bda2f](https://github.com/wazuh/wazuh-ansible/commit/f8bda2f7c7c58e9559101c8b5fd224391913ed0f)

### New CA variables and adapted templates

When using custom CA, certs may have a custom name that needs to be managed. To satisfy this requirement, 3 new parameters has been added

https://github.com/wazuh/wazuh-ansible/blob/8234bb11d2ba24ac94eef7ebba1c1b76f64b7926/roles/elastic-stack/ansible-elasticsearch/defaults/main.yml#L28-L33

Where `generate_CA` is the flag that enables the configuration using a custom CA.

**Important note:** According to ES standard, the ca must be in the path specified in `master_destination_folder` and under the `/ca/` folder 

### New task to generate cert using pem keys and cert

The ES binary provides different modifiers that allow configuring the certificates generation.

In order to use the custom CA, the binary parameters must be modified:

https://github.com/wazuh/wazuh-ansible/blob/4b8303ece281ffb3a61d9407e51484bb8686325e/roles/elastic-stack/ansible-elasticsearch/tasks/xpack_security.yml#L68-L75

### CA certificate progation

The CA cert is now copied on the generator in order to use them in the ES binary.

You can check the changes at [#01d4cfc](https://github.com/wazuh/wazuh-ansible/commit/01d4cfc1288adaa0d7c2f78e7fe19ca4eba880ec)

Best regards

Jose

**Comment by jm404** [comment]
Hi team,

Today's efforts where aimed to:

#### Fix certificates permissions

The certificates are now copied properly configuring the owner and group and the execution permissions.

The changes were applied in [#61637a7](https://github.com/wazuh/wazuh-ansible/commit/61637a7b39a2ab33267f7cc8bbcef5e47d8aa574)

#### Give support to PKCS12

The importing and generation of PKCS12 is now possible. Parameters have been updated and new tasks have been implemented in order to import the CA and configure the elasticsearch-certutil binary execution.

https://github.com/wazuh/wazuh-ansible/blob/e4b0e583822a8ef3f252740897ec3029715605ba/roles/elastic-stack/ansible-elasticsearch/tasks/xpack_security.yml#L89-L115

You can check the changes at: [#e4b0e58](https://github.com/wazuh/wazuh-ansible/commit/e4b0e583822a8ef3f252740897ec3029715605ba) & [#41499d0](https://github.com/wazuh/wazuh-ansible/commit/41499d007504e3bce96554c090124113cc79904c)

Best regards

Jose

**Comment by jm404** [comment]
Done in https://github.com/wazuh/wazuh-ansible/pull/199
