### ISSUE TITLE
Wazuh Agent installation fails on Windows

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#233]
Hi team,

The Wazuh Agent fails on Windows installation with different errors that need to be fixed.

#### Tasks

- [x] Check if agent is installed (fails sometimes, checking the ossec.exe is not enough)

- [x] Test: Install Wazuh-Agent on both paths (x86 and x64)

- [x] Test: Install Wazuh-Agent on a host with already installed Wazuh-Agent

- [x] Test: Upgrade Agent

Best regards

Jose
