### ISSUE TITLE
Ansible doesn't upgrade properly from 6.x to 7.x

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#250]
Hi team,

It was reported that Ansible was not installing the latest version of elastic when doing an upgrade from 6.x version.

I diagnosed some errors:

- The repository is named "elastic_repo" for 6.x and 7.x url, making ansible not adding the new repository

- The "Checking Wazuh-APP version" is not working properly, the return code is never "0"  and doesn't upgrade the Kibana plugins on the host

### Tasks

- [x] Rename 7.x repository to avoid conflicts with previous one

- [x] Fix tasks that updates the Kibana plugin

- [x] Do a manual upgrade following https://www.elastic.co/guide/en/elasticsearch/reference/7.3/rolling-upgrades.html , installing new components with Ansible

- [x] Ensure Kibana and ES version = 7.3.2

- [x] Ensure Wazuh version = 3.10.2

Best regards

Jose
