### ISSUE TITLE
Unzip is required (on the Ansible master) on a distributed elastic xpack scenario

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-ansible#254]
Hi team,

## Description

On a distributed elastic scenario (with xpack enabled) the playbook requires the `unzip` utlity to be installed on the Ansible master. There's no clear way of doing this automatically.

I propose detecting installed packages and failling if not found, with a helpful message of course.

## Tasks
- [x] Detect packages on the Ansible master
- [x] Fail if unzip not found and show an error message with instructions
- [x] Document unzip requirement on the playbook Readme

Regards.
