### ISSUE TITLE
SCA is not defined in the Wazuh Manager and Wazuh Agent templates

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#256]
Hi team,

The Wazuh Agent/Manager installation doesn't include the `<sca>` configuration block in the `ossec.conf` file.

This block is included and enabled in a default installation and should be added in order to make use of SCA functionalities

### Tasks:

- [x] Implement `<sca>` block in the Wazuh templates

- [x] Add related variables to enable and configure this block

- [x] Test configuration with different variables values

Best regards, 

Jose

**Comment by jm404** [comment]
Hi team,

I updated the template in the Wazuh Manager and Wazuh Agent adding the following configuration:

https://github.com/wazuh/wazuh-ansible/blob/d45ad1db03538c8935ad57c0132f2e78bf96eb89/roles/wazuh/ansible-wazuh-agent/templates/var-ossec-etc-ossec-agent.conf.j2#L273-L298

Also, related values are now initialized by default:

https://github.com/wazuh/wazuh-ansible/blob/7371e7392041fe1753073290e231acf143ee8b71/roles/wazuh/ansible-wazuh-manager/defaults/main.yml#L157-L164

From Wazuh 3.10, SCA no longer contains the `<policy>` field relative to every OS, making much easier to mantain the specified template in Jinja2

Best regards,

Jose
