### ISSUE TITLE
Wazuh Ansible Agent msi installer compatibility with different windows versions is not tested.

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#264]
Hi team,

The task that verifies Windows Agents contains the `product_id` which is required by the `win_package` module in Ansible:

https://github.com/wazuh/wazuh-ansible/blob/120ed163b6f131315848938beca65c1f1cad7f1b/roles/wazuh/ansible-wazuh-agent/tasks/Windows.yml#L42-L47

![image](https://user-images.githubusercontent.com/46649922/65985525-4968d800-e482-11e9-8d7a-091d70936fdf.png)

This `product_id` has not been tested in different Windows and could cause incompatibility to different versions

### Tasks

- [x] Evaluate the better solution to give compatibility to different Windows versions

- [x] Implement the changes 

- [x] Test the changes

- [x] Update CHANGELOG.md

- [x] Review the linting with `ansible-lint`

Best regards

Jose
