### ISSUE TITLE
Wazuh Agent doesn't render specific localfiles in Redhat os families

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#267]
Hi team,

The current template for Wazuh Agent doesn't render the localfiles for RedHat families including Amazon Linux 2.

The template accepts the required variables:

https://github.com/wazuh/wazuh-ansible/blob/d384c7397f3182b58b472ffd01e8c8b5d7a9f3ed/roles/wazuh/ansible-wazuh-agent/templates/var-ossec-etc-ossec-agent.conf.j2#L321-L336

But the default localfiles for RHEL are not declared in the defaults variables:

https://github.com/wazuh/wazuh-ansible/blob/d384c7397f3182b58b472ffd01e8c8b5d7a9f3ed/roles/wazuh/ansible-wazuh-agent/defaults/main.yml#L263-L304

### Tasks

- [ ] Obtain the default syslog and update the template

- [ ] Check template is rendered properly

- [ ] Verify the alerts related to the changes are properly generated

Best regards

Jose

**Comment by jm404** [comment]
Hi all,

The default case covers the different RedHat families, this issue is no longer required.

Best regards,

Jose
