### ISSUE TITLE
Filebeat.yml file is not updated to latest version

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#271]
Hi all,

The `filebeat.yml` template in the ansible-filebeat role is the following.

https://github.com/wazuh/wazuh-ansible/blob/d384c7397f3182b58b472ffd01e8c8b5d7a9f3ed/roles/wazuh/ansible-filebeat/templates/filebeat.yml.j2#L1-L73

This template is not updated to the latest versions and doesn't make use of the Wazuh Filebeat Module:

https://github.com/wazuh/wazuh/blob/ee0943daae73677c3ff886b9ac892711fdf4ceeb/extensions/filebeat/7.x/filebeat.yml#L1-L15

It's required to update the template to make use of the latest features of Wazuh

## Tasks

- [ ] Update Filebeat template

- [ ] Deploy using variables to verify that are properly rendered

- [ ] Verify code syntax with `ansible-lint`

- [ ] Update changelog.md

Best regards,

Jose
