### ISSUE TITLE
Openscap template block may render invalid wodle block in ossec.conf

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#279]
The `openscap` block in the template [var-ossec-etc-ossec-server.conf.j2](https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-manager/templates/var-ossec-etc-ossec-server.conf.j2) is not properly rendered for Centos 8 and RHEL 8.

The code block causing the issue is the following:

https://github.com/wazuh/wazuh-ansible/blob/d384c7397f3182b58b472ffd01e8c8b5d7a9f3ed/roles/wazuh/ansible-wazuh-manager/templates/var-ossec-etc-ossec-server.conf.j2#L133-L183

In RHEL8, as neither `{% if ansible_distribution_major_version == '7' %}` nor `{% elif ansible_distribution_major_version == '6' %}` are activated, the wodle is rendered as:

```
  <wodle name="open-scap">
    <disabled>no</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>
    
      
        <profile>xccdf_org.ssgproject.content_profile_pci-dss</profile>
        <profile>xccdf_org.ssgproject.content_profile_common</profile>
      </content>
    
  </wodle>

```

Notice **there is no line that opens "content" that tag** causing Wazuh Manager to fail when verifying the `ossec.conf` file.

This error affects different OS's and the following templates should be reviewed.

- [var-ossec-etc-ossec-server.conf.j2](https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-manager/templates/var-ossec-etc-ossec-server.conf.j2)

- [var-ossec-etc-ossec-agent.conf.j2](https://github.com/wazuh/wazuh-ansible/blob/master/roles/wazuh/ansible-wazuh-agent/templates/var-ossec-etc-ossec-agent.conf.j2)

### Tasks

- [x] Fix conditionals to don't render the wodle when OS can't be determined

- [x] Review rendered OS and update them if required

- [x] Test changes and verify template renders properly where OS detected

- [ ] Update changelog

Best regards

Jose
