### ISSUE TITLE
Allow to tune up disk space requirements for elasticsearch

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-ansible#280]
## Description

Recently we detected an unusual issue in our test environment https://github.com/wazuh/wazuh-qa/issues/210

We need a setting to allow the execution of this playbook on environments with low disk space percentage.

Mind that "low disk space percentage" doesn't always means "low disk space", ES default value  for `cluster.routing.allocation.disk.watermark.low` is 85% which in a 1TB machine would be 150GB free, enough for running a few tests.

This setting is mostly for testing environments, for production the default values are recommended.

## Tasks

- [x] Add a new variable to the ES defaults `elasticsearch_lower_disk_requirements`
- [x] Write low memory requirements to the ES config if variable is detected
- [x] Run a full test of the new settings

**Comment by manuasir** [comment]
Done here #281
