### ISSUE TITLE
Fix logic conditional of wazuh-manager tasks regarding OS platform

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#284]
**Wazuh version:** 3.10.0 and 3.10.2

**Elastic version:** 7.3.2

**Environment:**

Not relevant

**Is this a bug report or a feature requests?:**

Bug report

**What is the current behavior?**

Wazuh Manager tasks contains a wrong declared condional which passes tasks on some OS

**What is the motivation/use case for changing the behavior?**

Fix the conditional and update it to execute the task on supported OSs

**Description**: 

As @sgargel noticed on https://github.com/wazuh/wazuh-ansible/commit/d3784b4727027c712c9b7332d8409d2d0ee375ad the logic of the conditional has changed, making it to fail with some OS's like Debian 9

I also noticed that `ansible_distribution_major_version|int < 6` might not be needed anymore

### Tasks

- [ ] Fix conditional logic

- [ ] Evaluate if `ansible_distribution_major_version|int < 6` is required

- [ ] Pass the tests

Best regards,

Jose

**Comment by sgargel** [comment]
Take a look to https://github.com/wazuh/wazuh-ansible/pull/283#event-2741556020

**Comment by jm404** [comment]
Done in https://github.com/wazuh/wazuh-ansible/pull/283/files
