### ISSUE TITLE
Remove hardcoding of Wazuh repositories

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#287]
**Wazuh version:** 3.10.2

**Elastic version:** 7.3.2

**Environment:**
N/A

**Is this a bug report or a feature requests?:**
Feature Request

**What is the current behavior?**
The Wazuh repositories `gpg` and `baseurl` is hardcoded

**What is the motivation/use case for changing the behavior?**
Avoid hardcoding of Wazuh Repositories to be ready for repository changes.

**Description**:

### Tasks

- [x] Remove hardcoding of Yum repositories

- [x] Remove hardcoding of APT repositories

- [x] Verify installation on RHEL and Debian families

Best regards,

Jose

**Comment by jm404** [comment]
### Make repositories flexible

Repositories URLs are now dynamic. They are initialized in default vars:

![image](https://user-images.githubusercontent.com/46649922/67713024-561b1600-f9c5-11e9-82e1-7e0d498418da.png)

Related tasks that manage the repositories have been updated to make use of these variables. 

Also, the GPG key is not hardcoded anymore. The 

![image](https://user-images.githubusercontent.com/46649922/67713089-73e87b00-f9c5-11e9-9e2e-8347f186c943.png)

Check https://github.com/wazuh/wazuh-ansible/pull/288 for detailed info about changes

Best regards

Jose
