### ISSUE TITLE
Add parameters to configure an Elasticsearch coordinating node

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#291]
**Wazuh version:** Any

**Elastic version:** Any

**Environment:**

Any

**Is this a bug report or a feature requests?:**

Feature request

**What is the current behavior?**

It's not possible to define `node.data` and `node.ingest` which make impossible to configure a coordinating only that works with Kibana as described in [Using Kibana in production](https://www.elastic.co/guide/en/kibana/current/production.html) guide from Elastic.

**What is the motivation/use case for changing the behavior?**

Implement required changes to make possible to install a Coordinating only ES.

**Description**: 

Some of the tasks that must be performed are:

### Tasks

- [x] Add required variables

- [x] Update the  `elasticsearch.yml` template with the new variables

- [x] Test that when setting to false, the settings are being rendered properly

Best regards,

Jose
