### ISSUE TITLE
Wazuh Agent name is variable is not defined by default and variable naming is not standard

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#298]
**Wazuh version:** master & devel branches

**Elastic version:** master & devel branches

**Environment:**

Any

**Is this a bug report or a feature requests?:**

Feature request

**What is the current behavior?**

The variable to define the Wazuh Agent name in authd registration is `agent_name`. Such variable is not defined by default and does not accomplish with the naming convention

**What is the motivation/use case for changing the behavior?**
Rename the variable and initialize it by default to make it clearer when registering Wazuh Agents

**Description**: 

The tasks that need to be done to close this are:

### Tasks

- [x] Rename variable and initalize it by default

- [x] Test registration with different Agent names

- [x] Update documentation and changelog

Best regards,

Jose
