### ISSUE TITLE
Wazuh Agent does not explicitly restart after registering the Agent

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#300]
**Wazuh version:** 3.10.2 

**Elastic version:** 7.3.2

**Environment:**

Any

**Is this a bug report or a feature requests?:**

Bug request

**What is the current behavior?**

Registration tasks in the `ansible-wazuh-agent` role do not restart the Wazuh Agent after registering it, such task is delegated to following tasks that in some situations are not executed. This can lead to an Agent re-registering but not 

**What is the motivation/use case for changing the behavior?**

Notifying the restart of the Agent after registering will ensure the Agent is properly registered.

**Description**: 

### Tasks

- [x]  Add `notify` to Agent registration tasks

- [x] Ensure the Agent re-register itself and restart after removing it's `client.keys` file

- [x] Update documentation and CHANGELOG.md

Best regards,

Jose

**Comment by jm404** [comment]
### Add `notify` to registration tasks

The registration tasks for Linux Wazuh Agents have been updated to notify the restart of the Agent This way we ensure it's restarted after every registration even if the configuration files do not change.

![image](https://user-images.githubusercontent.com/46649922/68217240-92acca00-ffe2-11e9-8ed8-ab0a8df175ff.png)

**Commit:https://github.com/wazuh/wazuh-ansible/commit/b6ccd7020e78a192162f711ca3dc515d1fa38e4b**
