### ISSUE TITLE
Remove hardcoding of Wazuh Kibana app URL

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#303]
**Wazuh version:** 3.10.2

**Elastic version:** 7.3.2

**Environment:**

Any

**Is this a bug report or a feature requests?:**

Feature request

**What is the current behavior?**

The task that installs Wazuh-APP has the repository URL hardcoded. 

**What is the motivation/use case for changing the behavior?**

Make the URL flexible so we can install different app versions from different sources.

**Description**: 

### Tasks

- [x] Create a variable that contains the Wazuh App URL and update related task

- [x] Test the installation of Apps from different sources

- [x] Update documentation and CHANGELOG.md

Best regards,

Jose

**Comment by jm404** [comment]
### Remove hardcoding of Wazuh APP URL

I simply added an url that will define the URL from where the Wazuh App is pulled and updated the related task:

![image](https://user-images.githubusercontent.com/46649922/68221536-dbb44c80-ffe9-11e9-96a9-b516323b1e4f.png)


**Commit:** https://github.com/wazuh/wazuh-ansible/pull/304/commits/5684805d5539b264669868b1013dd4854b208622  & https://github.com/wazuh/wazuh-ansible/pull/304/commits/483a543c76fc6f6017237b2a15f59364c4bb51ef
