### ISSUE TITLE
Openscap wodle and should not be enabled by default

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#305]
**Wazuh version:** 3.10.2

**Elastic version:** 7.3.2

**Environment:**

Any

**Is this a bug report or a feature requests?:**
Feature request

**What is the current behavior?**

Open-SCAP wodle is enabled by default which renders the wodle and installs required dependencies

**What is the motivation/use case for changing the behavior?**

Disable Open-SCAP by default to match the default installation of Wazuh to avoid installing unrequired dependencies.

**Description**: 

### Tasks:

- [x] Disable OpenSCAP by default 

- [x] Verify installations on Manager and Agent

- [x] Update documentation if required

Best regards,

Jose
