### ISSUE TITLE
The python-cryptography is no longer required

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#306]
**Wazuh version:** 3.10.2

**Elastic version:** 7.3.2

**Environment:**

Any

**Is this a bug report or a feature requests?:**
Feature request

**What is the current behavior?**

The dependency `python-cryptography` is installed explicitly in some of the Ansible tasks.

**What is the motivation/use case for changing the behavior?**

This is no longer necessary as that library is already included in Wazuh

**Description**: 

### Tasks

- [x] Remove tasks related with `python-cryptography`

- [x] Test the installation on different OS's

- [ ] Update documentation if required

Best regards,

Jose

**Comment by NerdsvilleCEO** [comment]
Is this being worked on? I am working on installing this, and as such am getting errors with this package, I can work on this if need be

**Comment by jm404** [comment]
Hi @NerdsvilleCEO,

We have not tackled that issue yet but it shouldn't be big trouble, we will work on it very soon.

The issue will be included in the milestone as soon as we start working on it and you will be able to see updates about the changes in the issue.

Best regards!

**Comment by NerdsvilleCEO** [comment]
Oh alright, I already removed it from the installation locally so just let me know and I can form a PR

**Comment by manuasir** [comment]
Done here #401 , thanks @NerdsvilleCEO for reporting this.
