### ISSUE TITLE
Optimize manager install process

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-ansible#317]
### Description

The manager role is taking an odly long time fo the installation process, and consequently, for the tests.

Let's find out if there's any chance to lower those execution times.

### Tasks
- [x] Profile the manager role
- [x] Apply any possible speed improvement
- [x] Test role execution on all platforms

**Comment by xr09** [comment]
First some playbook profiling with the [profile_tasks](https://docs.ansible.com/ansible/latest/plugins/callback/profile_tasks.html) plugin.


I started profiling our Elasticsearch playbook, it is a good point of reference to start our quest.

```
Elasticsearch
=============

Install Elasticsarch ------------------------------------------- 35.85s
Make sure Elasticsearch is running before proceeding ----------- 14.33s
Install apt-transport-https and ca-certificates ---------------- 6.78s
Install Elastic repo ------------------------------------------- 2.32s
Removing Elasticsearch repository ------------------------------ 2.19s


Wazuh Manager
=============

Install wazuh-manager, wazuh-api ------------------------------- 92.47s
Install OpenScap ----------------------------------------------- 11.36s
Install apt-transport-https and ca-certificates ---------------- 8.22s
Install expect ------------------------------------------------- 7.18s
restart wazuh-manager ------------------------------------------ 6.25s
Install dependencies ------------------------------------------- 5.42s
```

Profiling the actual steps with `time apt install`

```
apt install wazuh-manager..... 0m32.533s
apt install wazuh-api ........ 1m1.476s
```

**Comment by xr09** [comment]
APT has an `install-recommends` flag which is enabled by default for Debian and Ubuntu, and Ansible's apt module leaves this flag untouched. Tuning this value could yield some improvements.

This is the output using `install_recommends: no` on the apt tasks:

```
Install wazuh-manager, wazuh-api ------------------------------- 59.91s
Install OpenScap ----------------------------------------------- 11.15s
Install apt-transport-https and ca-certificates ---------------- 8.27s
Install expect ------------------------------------------------- 6.80s
restart wazuh-manager ------------------------------------------ 5.57s
Install dependencies ------------------------------------------- 5.39s
```

We can appreciate the manager/api task takes roughly 30 seconds less.

**Comment by xr09** [comment]
Another possible optimization (albeit purely graphical) is the switch from `import_tasks` to `include_tasks`, omitting this way unnecessary `skipped` tasks on the output.
