### ISSUE TITLE
Explore solutions to improve the variables configuration for Wazuh Ansible roles

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#318]
**Wazuh version:** Any

**Elastic version:** Any

**Environment:** Any

**Is this a bug report or a feature requests?:**
Feature request

**Description**: 

When declaring variables in a playbook like:
```
  - hosts: managers
    roles:
      - role: "/tmp/wazuh-ansible/roles/wazuh/ansible-wazuh-manager"
        wazuh_manager_version: 3.10.2-1
        wazuh_manager_config:
          cluster:
            disable: 'no'
            name: 'wazuh'
            node_name: 'manager_01'
            node_type: 'worker'
            key: 'xx'
            port: '1516'
            bind_addr: '0.0.0.0'
            nodes:
              - '10.0.0.xx'
            hidden: 'no'
```

By default, Ansible will override the whole [wazuh_manager_config](https://github.com/wazuh/wazuh-ansible/blob/d384c7397f3182b58b472ffd01e8c8b5d7a9f3ed/roles/wazuh/ansible-wazuh-manager/defaults/main.yml#L7-L267), making the rest of the keys disappear.

In order to merge variables instead of overriding them, an Ansible config variable can be set in `/etc/ansible/ansible.cfg`
```
hash_behaviour = merge
```

But this can cause incompatibilities for users with other playbooks and is discouraged.

A possible solution could come from using [combine](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#combining-hashes-dictionaries) method to merge both dicts.

It's required to explore approaches for this and implement required changes to avoid forcing the usage of `hash_behaviour`

### Tasks

- [ ] Explore and test different approaches for this

- [ ] Verify compatibility with default Ansible configurations

- [ ] Update documentation related to this

Best regards

Jose

**Comment by jm404** [comment]
Duplicate of #101
