### ISSUE TITLE
Add support to sources installation for Wazuh Manager, Agent and Kibana APP

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#324]
Hi all,

The current Ansible Playbooks allow the installation from packages but the compilation from sources is not supported yet.

Such compilation is really useful as any user could add his own improvements or any change from `wazuh/wazuh` repository that has not been released yet.

### Tasks

- [x] Add required tasks to install and configure dependencies for building the Wazuh Packages

- [x] Add tasks to compile Wazuh Manager

- [x] Add tasks to compile Wazuh Agent

- [x] Add tasks to compile Wazuh Kibana Plugin

- [x] Tests Manager compilation, installation and configuration using implemented changes

- [x] Tests Agent compilation, installation and configuration using implemented changes

Best regards

Jose

**Comment by jm404** [comment]
### Add required default variables to configure installation from sources

Every setting stated in [Unattended Installation] (https://documentation.wazuh.com/3.10/user-manual/reference/unattended-installation.html#unattended-installation) has been added as a variable in order to make the sources installation fully customizable

![image](https://user-images.githubusercontent.com/46649922/69259888-40150580-0bbf-11ea-9ba2-a75f6ec672bd.png)

*Note: The image shows "enabled: True" but by default will be set to False*

**Commits:** https://github.com/wazuh/wazuh-ansible/commit/b3a2fea6b94616726e2d6250915eb71b55fc1285 && https://github.com/wazuh/wazuh-ansible/commit/c1b331be79ef28cb4bb768d45879523009f9777a

### Add "install_from_sources.yml"

This file will contain the required tasks to install and configure the Wazuh Manager and Agents from sources.

That file is duplicated for `ansible-wazuh-agent` and `ansible-wazuh-manager` roles. It's done to give room for when the roles get published in Ansible Galaxy so users can install from sources both, Manager and Agent.

https://github.com/wazuh/wazuh-ansible/blob/e0038118e1ffb2a02ee39d733cff0c26138e5afe/roles/wazuh/ansible-wazuh-manager/tasks/installation_from_sources.yml#L1-L70
