### ISSUE TITLE
Update Wazuh API Installation

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#326]
Hi all,

The Wazuh API installation is currently done with:

https://github.com/wazuh/wazuh-ansible/blob/c2ae0bf9bd17c9faca21ecb191bbaf59a2a27d23/roles/wazuh/ansible-wazuh-manager/tasks/RedHat.yml#L2-L11

Which is currently outdated. It's required to update it according to the [Wazuh Documentation](https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-manager/linux/amazon/wazuh_server_sources_amazon.html#installing-wazuh-api)

### Tasks:

- [x] Update API tasks for RedHat and Debian families

- [x] Update conditionals and remove `AmazonLinux | Get Nodejs` task

- [x] Test installation on both OS families and ensure API is correctly installed

Best regards

Jose

**Comment by rshad** [comment]
Working Branch: [feature-326-wazuh-api-installation](https://github.com/wazuh/wazuh-ansible/tree/feature-326-wazuh-api-installation)

**Comment by rshad** [comment]
Hi all!

We reformulated the tasks so we follow the latest documentation from Wazuh.

Changes can be resumed as:

- Add task to check if node service already exists (RedHat) 686c02b3d5d424356bde2df86ed335fb7276291b

https://github.com/wazuh/wazuh-ansible/blob/686c02b3d5d424356bde2df86ed335fb7276291b/roles/wazuh/ansible-wazuh-manager/tasks/RedHat.yml#L2-L4

- Adapt NodeJS installation tasks for Debian 4dd780504b0669d6aa7d77fea5711cf58c312b9d

https://github.com/wazuh/wazuh-ansible/blob/686c02b3d5d424356bde2df86ed335fb7276291b/roles/wazuh/ansible-wazuh-manager/tasks/Debian.yml#L41-L49

- Adapt NodeJS installation tasks for Amazon/Fedora 3c70bc5b2a1e7505971090867378f72fa9219249

https://github.com/wazuh/wazuh-ansible/blob/686c02b3d5d424356bde2df86ed335fb7276291b/roles/wazuh/ansible-wazuh-manager/tasks/RedHat.yml#L6-L25

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

After getting a first valid version of the requested configuration, we thought about having a more efficient and better designed Ansible configuration. This improvement is based on the implementation of the following 3 points:

1- **Try to use Ansible modules** instead of some alternatives like (shell: curl ....)
2- **Use the `package` module to unify the packages installation** instead of using `yum_repository` and `apt` for each of RedHat and Debian distributions respectively.
3- **Centralize the common configurations** in `main.yml` instead of repeating them for each distribution separately.

**Tasks**

To do so, we added the following configuration.

- Removed all the tasks related to NodeJS installation from both tasks files:
- - [roles/wazuh/ansible-wazuh-manager/tasks/Debian.yml](https://github.com/wazuh/wazuh-ansible/blob/feature-326-wazuh-api-installation/roles/wazuh/ansible-wazuh-manager/tasks/Debian.yml)
- - [roles/wazuh/ansible-wazuh-manager/tasks/RedHat.yml](https://github.com/wazuh/wazuh-ansible/blob/feature-326-wazuh-api-installation/roles/wazuh/ansible-wazuh-manager/tasks/RedHat.yml)

- - **Related Commits**
- - - https://github.com/wazuh/wazuh-ansible/commit/d85d210a3e5029253b0a30276e60d35233ab8fa1
---
- Centralize all the needed configurations "Tasks" in the role's `main.yml` file

- - Added a task to check if `node` service is already installed on the system.
https://github.com/wazuh/wazuh-ansible/blob/565a84c49f801c934bcecffeda47b7356e334584/roles/wazuh/ansible-wazuh-manager/tasks/main.yml#L10-L13

- - `**If Not Then Run**` Added a `Block` of two `tasks` to download the NodeJS repository bash script and to install the downloaded script.
https://github.com/wazuh/wazuh-ansible/blob/565a84c49f801c934bcecffeda47b7356e334584/roles/wazuh/ansible-wazuh-manager/tasks/main.yml#L15-L28


- - Added a task to install NodeJs.

*`Note`*:  This task will run in both cases, when NodeJS is already installed or it's not, but using Ansible `package` module, will prevent it from being executed if `node` is installed and then no `Idempotecne` errors are produced.
https://github.com/wazuh/wazuh-ansible/blob/565a84c49f801c934bcecffeda47b7356e334584/roles/wazuh/ansible-wazuh-manager/tasks/main.yml#L30-L36
 
----

**Variables**

As you can see in the task "Download NodeJS repository script"

https://github.com/wazuh/wazuh-ansible/blob/565a84c49f801c934bcecffeda47b7356e334584/roles/wazuh/ansible-wazuh-manager/tasks/main.yml#L17-L22

We use a dictionary `repo_dic` to check to which distribution, NodeJS repository should be downloaded; so in  

- [wazuh-ansible/roles/wazuh/ansible-wazuh-manager/defaults/main.yml](https://github.com/wazuh/wazuh-ansible/blob/feature-326-wazuh-api-installation/roles/wazuh/ansible-wazuh-manager/defaults/main.yml)

We added the definition of `repo_dic` as follows:
https://github.com/wazuh/wazuh-ansible/blob/565a84c49f801c934bcecffeda47b7356e334584/roles/wazuh/ansible-wazuh-manager/defaults/main.yml#L329-L331


Kr,

Rshad
