### ISSUE TITLE
Wazuh Release 3.11.0_7.5.1

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#336]
Wazuh version: 3.11.0
Elastic version: 7.5.1

### Tasks

- [ ] Adapt to new versions (3.11.0 - 7.5.1)

- [ ] Check templates and update them if needed

- [ ] Update changelog

- [ ] Update documentation references

- [ ] Pass Molecule tests

- [ ] Tag: v3.11.0_7.5.1

- [ ] Draft release
