### ISSUE TITLE
Wazuh Release 3.11.1_7.5.1

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#341]
Wazuh version: 3.11.1
Elastic version: 7.5.1

### Tasks

- [x] Adapt to new versions (3.11.1 - 7.5.1)

- [x] Check templates and update them if needed

- [x] Update Windows MD5 hash

- [x] Update changelog

- [x] Update documentation references

- [x] Pass Molecule tests

- [ ] Tag: v3.11.1_7.5.1

- [ ] Draft release

**Comment by xr09** [comment]
The PR is currently failing on Kibana tests, our current scenario is a single Kibana hosts and it's missing Elastic connectivity when attempting to delete the `.wazuh` index.

Working a fix for this.

**Comment by xr09** [comment]
This is happening because the Kibana scenario is isolated and has no connectivity with Elasticsearch, a posible fix would be merging both scenarios.

**Comment by xr09** [comment]
Working on this on QA repo https://github.com/wazuh/wazuh-qa/issues/371

**Comment by tk129909** [comment]
> The PR is currently failing on Kibana tests, our current scenario is a single Kibana hosts and it's missing Elastic connectivity when attempting to delete the `.wazuh` index.
> 
> ```
> 
>  TASK [elastic-stack/ansible-kibana : Wait for Elasticsearch port] **************
>     fatal: [kibana-centos7]: FAILED! => {"changed": false, "elapsed": 60, "msg": "Timeout when waiting for elasticsearch-centos7:9200"}
>     
>     TASK [elastic-stack/ansible-kibana : Attempting to delete legacy Wazuh index if exists] ***
>     fatal: [kibana-centos7]: FAILED! => {"changed": false, "content": "", "msg": "Status code was -1 and not [200, 404]: Request failed: <urlopen error [Errno -2] Name or service not known>", "redirected": false, "status": -1, "url": "http://elasticsearch-centos7:9200/.wazuh"}                                                                       
>  
> ```
> 
> Working on a fix for this.

Please give detail to solve this problem.

**Comment by tk129909** [comment]
> > The PR is currently failing on Kibana tests, our current scenario is a single Kibana hosts and it's missing Elastic connectivity when attempting to delete the `.wazuh` index.
> > ```
> > 
> >  TASK [elastic-stack/ansible-kibana : Wait for Elasticsearch port] **************
> >     fatal: [kibana-centos7]: FAILED! => {"changed": false, "elapsed": 60, "msg": "Timeout when waiting for elasticsearch-centos7:9200"}
> >     
> >     TASK [elastic-stack/ansible-kibana : Attempting to delete legacy Wazuh index if exists] ***
> >     fatal: [kibana-centos7]: FAILED! => {"changed": false, "content": "", "msg": "Status code was -1 and not [200, 404]: Request failed: <urlopen error [Errno -2] Name or service not known>", "redirected": false, "status": -1, "url": "http://elasticsearch-centos7:9200/.wazuh"}                                                                       
> >  
> > ```
> > 
> > 
> > Working on a fix for this.
> 
> Please give detail to solve this problem.

Kibana is OK, Elastic is OK but the task fail error still continues
