### ISSUE TITLE
Wazuh Ansible Release 3.11.2_7.5.1

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#349]
Wazuh version: 3.11.2
Elastic version: 7.5.1

### Tasks

- [x] Adapt to new versions (3.11.2 - 7.5.1)

- [x] Check templates and update them if needed

- [ ] Update Windows MD5 hash

- [ ] Update changelog

- [ ] Update documentation references

- [ ] Pass Molecule tests

- [ ] Tag: v3.11.2_7.5.1

- [ ] Draft release
