### ISSUE TITLE
Wazuh Ansible Release 3.11.3_7.5.2

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#355]
Wazuh version: 3.11.3
Elastic version: 7.5.2

### Tasks

- [x] Adapt to new versions (3.11.3 - 7.5.2)

- [x] Check templates and update them if needed

- [ ] Update Windows MD5 hash

- [x] Update changelog

- [x] Update documentation references

- [ ] Pass Molecule tests

- [ ] Tag: v3.11.3_7.5.2

- [ ] Draft release
