### ISSUE TITLE
Installation from packages (.rpm and .deb)

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#365]
### Objective

The main point is to add required tasks to allow the Wazuh installation from custom packages. This way, users will be able to install Wazuh using custom or nightly packages in conjunction with the `wazuh-ansible` repositories

### Tasks

- [x] Create required variables to enable packages installation 

- [x] Installation of Wazuh Manager

- [x] Installation of Wazuh Agent

- [x] Test installation using custom packages

Best regards,

Jose

**Comment by jm404** [comment]
Done in #366
