### ISSUE TITLE
Install Window's Wazuh Agent from custom URL

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#367]
Hi all,

The current code doesn't allow the users to install the Window's Wazuh Agent from a custom URL as it's semi-hardcoded:

https://github.com/wazuh/wazuh-ansible/blob/2375dedfb8da3e7d77721e0fc1ecc9d7f5e129f2/roles/wazuh/ansible-wazuh-agent/tasks/Windows.yml#L21-L45

It's required to add required changes so users can install a custom .msi package from different repositories and with different names.

### Tasks

- [x] Update required variables, remove dict format

- [x] Change occurrences of old variables

- [x] Test installation from different URLs

Best regards,

Jose

**Comment by jm404** [comment]
Done in #368
