### ISSUE TITLE
Support Centos 8

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#376]
Hi all,

RHEL8 and Centos 8 make use of the new package manager [dnf](https://fedoraproject.org/wiki/DNF?rd=Dnf). It's required to update all `yum` tasks to give our playbooks compatibility with previously mentioned Operating Systems.

### Tasks

- [x] Review every `yum` block and implement an alternative task using Ansible `dnf` module.

- [x] Run tests on Centos 8 using Python3 interpreter and manually review them

- [ ] Pass CI tests

Best regards,

Jose
