### ISSUE TITLE
Wazuh Ansible Release 3.11.4_7.6.1

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-ansible#379]
Wazuh version: 3.11.4
Elastic version: 7.6.1

### Tasks

- [x] Adapt to new versions (3.11.4 - 7.6.1) 3f0e032

- [x] Check templates and update them if needed

- [x] Update Windows MD5 hash c3dd95c

- [x] Update changelog 3f0e032

- [x] Update documentation references https://github.com/wazuh/wazuh-documentation/pull/2261

- [x] Pass Molecule tests

- [x] Tag: v3.11.4_7.6.1

- [x] Draft release
