### ISSUE TITLE
Update Wazuh Manager and Wazuh Agent configuration templates to Wazuh 3.12 

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-ansible#394]
Hi team,
### Objective:

The Wazuh Agent/Manager installation should include new Wazuh 3.12 configuration section blocks. The following is an example of a new `<syscheck>` section:

```XML
    <!-- Database synchronization settings -->
    <synchronization>
      <enabled>yes</enabled>
      <interval>5m</interval>
      <max_interval>1h</max_interval>
      <max_eps>10</max_eps>
    </synchronization>
```

This block is included and enabled in a default installation and should be added in order to make use of SCA functionalities

### Tasks:

- [x] Implement new blocks/sections in the Wazuh templates

- [x] Add related variables to enable and configure this blocks/sections

- [x] Test configuration with different variables values

Related branch: https://github.com/wazuh/wazuh-ansible/tree/feature-394-templates-update
Related PR: https://github.com/wazuh/wazuh-ansible/pull/398
Best regards, 

JP Sáez
