### ISSUE TITLE
Wazuh Ansible Release 3.12.0_7.6.1

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-ansible#395]
Wazuh version: 3.12.0
Elastic version: 7.6.1

### Tasks

- [x] Adapt to new versions (3.12.0 - 7.6.1) 

- [x] Check templates and update them if needed

- [x] Update Windows MD5 hash

- [x] Set custom packages URL to empty string

- [x] Update changelog

- [x] Update documentation references

- [x] Pass Molecule tests

- [x] Tag: v3.12.0_7.6.1

- [x] Draft release
