### ISSUE TITLE
Wazuh Ansible release v3.12.1_7.6.2

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-ansible#403]
Wazuh version: 3.12.1
Elastic version: 7.6.2

### Tasks

- [x] Adapt to new versions (3.12.1 - 7.6.2) 

- [x] Check templates and update them if needed

- [x] Update Windows MD5 hash

- [x] Set custom packages URL to an empty string

- [x] Update changelog

- [x] Update documentation references

- [x] Pass Molecule tests

- [ ] Tag: v3.12.1_7.6.2

- [ ] Draft release
