### ISSUE TITLE
Update Kibana Optimize tasks

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#411]
Hi team,

The Kibana optimize process takes more RAM than expected in 7.6.x versions and higher. When installing Kibana along with Elasticsearch, the RAM consumption exceeds the limits +90%, causing the OOMKiller to stop and kill Elasticsearch on systems with 8GB RAM or less.

https://github.com/wazuh/wazuh-ansible/blob/a69d63246887ddfabd691a20f99d4fa6a442ee00/roles/elastic-stack/ansible-kibana/tasks/main.yml#L138-L146 

After some debugging @Zenidd discovered that executing the kibana optimize using all the subparameters (avoiding the implicit interpolation made by Kibana) fixes the error:
```
sudo -u kibana /usr/share/kibana/node/bin/node --no-warnings --max-old-space-size=2048 --max-http-header-size=65536 /usr/share/kibana/src/cli --optimize
```

### Tasks

- [x] Update the optimize task with the specified parameters

- [x]  Ensure the installation properly works on hosts with less than in a single node architecture: Wazuh - Filebeat - Elasticsearch - Kibana

  - [x] 8GB

  - [ ] 4GB: FAILED, not enough RAM

  - [x] 5GB: Seems to be the minimum limit.

- [ ] Check that all services are properly working
  
  - [ ] Demo environment 

  - [x] Single host deployment

Best regards,

Jose

**Comment by jm404** [comment]
### Update optimize task

The task has been updated to execute the new command. Also, the related variable now contains more parameters.

![image](https://user-images.githubusercontent.com/46649922/79764804-21f63180-8326-11ea-87c2-b6ff5da01e4b.png)

https://github.com/wazuh/wazuh-ansible/commit/c6354e2ddc97271bfe9861eec760c33490c6077e

**Comment by manuasir** [comment]
Done here #412
