### ISSUE TITLE
Wazuh Ansible release v3.12.3_7.6.2

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ansible#414]
Wazuh version: 3.12.3
Elastic version: 7.6.2

### Tasks

- [ ] Adapt to new versions (3.12.3 - 7.6.2) 

- [ ] Check templates and update them if needed

- [ ] Update Windows MD5 hash

- [ ] Set custom packages URL to an empty string

- [ ] Update changelog

- [ ] Update documentation references

- [ ] Pass Molecule tests

- [ ] Tag: v3.12.3_7.6.2

- [ ] Draft release
