### ISSUE TITLE
Fetch ES template from wazuh/wazuh repository

### ISSUE THREAD

**Issue by jmgarcia404** [wazuh/wazuh-ansible#435]
Hi team,

The `wazuh-template.json` is being rendered on installations from:

https://github.com/wazuh/wazuh-ansible/blob/master/roles/elastic-stack/ansible-elasticsearch/templates/wazuh-elastic7-template-alerts.json.j2

This template is always located in https://github.com/wazuh/wazuh/blob/master/extensions/elasticsearch/7.x/wazuh-template.json which is updated in every version.

We should make the task that configures the template fetch it from the repo instead of rendering a static template. This will make deploys always work with the according template from wazuh/wazuh repo.

### Tasks

- [x] Change `template` task for a fetch task

- [x] Ensure owners and permissions

- [x] Test new change

Best regards,

Jose
