### ISSUE TITLE
Wazuh Ansible release v3.13.0_7.7.1

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-ansible#436]
Wazuh version: 3.13.0
Elastic version: 7.7.1

### Tasks

- [x] Adapt to new versions (3.13.0 - 7.7.1) 

- [x] Solve #435 issue (_Fetch ES template from wazuh/wazuh repository_)

- [x] Check templates and update them if needed

- [x] Update Windows MD5 hash

- [x] Update changelog

- [ ] Update documentation references

- [ ] Pass Molecule tests

- [ ] Tag: v3.13.0_7.7.1

- [ ] Draft release
