### ISSUE TITLE
Adapt roles to upcoming major Wazuh version

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-ansible#454]
Hi team,

Due to the next Wazuh major version, several changes will be involved such:

- [x] Remove Wazuh API package
- [x] Set TCP to default protocol
- [x] Create template for the new `api.yaml` API config file.
- [ ] Add support to create Wazuh-API users on wazuh-manager role. https://github.com/wazuh/wazuh-ansible/issues/457
- [x] Set index pattern to `wazuh-alerts-4.x`
- [x] Agent auto-enrollment

Current working branch: [feature-adapt-major-version](https://github.com/wazuh/wazuh-ansible/tree/feature-adapt-major-version)

We have to adapt every Ansible role to Wazuh v4.0, this issue is for tracking purposes and it will be updated frequently.

Regards

**Comment by manuasir** [comment]
We're almost done with this. Lately, we've been into the new `auto-enrollment` feature, mainly testing using the following `<enrollment>` block:

```
 <enrollment>
    <enabled>yes</enabled>
    <manager_address>192.168.1.100</manager_address>
    <port>1515</port>
    <agent_name>agent</agent_name>
    <groups>Group1</groups>
    <agent_address>192.168.0.110</agent_address>
    <ssl_cipher>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ssl_cipher>
    <server_ca_path>/path/to/server_ca</server_ca_path>
    <agent_certificate_path>/path/to/agent.cert</agent_certificate_path>
    <agent_key_path>/path/to/agent.key</agent_key_path>
    <authorization_pass>TopSecret</authorization_pass>
    <auto_method>no</auto_method>
    <delay_after_enrollment>20</delay_after_enrollment>
    <use_source_ip>no</use_source_ip>
  </enrollment>
```
