### ISSUE TITLE
Migrate Molecule tests from Jenkins to GitHub Actions

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-ansible#461]
Hi team,

### Objective

Currently, the Molecule tests for testing the Wazuh Ansible roles are integrated with our CICD flow using Jenkins https://github.com/wazuh/wazuh-qa/tree/master/ansible/wazuh-ansible. The main idea is to migrate them to GitHub Actions so we can lighten the load on our servers and also we make the flow more transparent to the community as well.

### Tasks

- [ ] Define the module's structure, use concurrency as much as possible without dismissing cascade errors.
- [ ] Use Docker to execute the Molecule tests, images must run systemd. Ideally, there would be only one Docker image, which is supposed to execute a dynamic `molecule test` command by receiving arguments in runtime (env vars).
- [ ] Review and move each testing scenario.

This issue is supposed to be updated.

Regards
