### ISSUE TITLE
Add upgrade features to wazuh-ansible roles

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-ansible#489]
Hi team,

## Description
Several users have asked about `wazuh-ansible` ability when it comes to upgrade the already installed roles. The current `wazuh-ansible` roles can't handle upgrades safely, i.e: User customized files are overwritten with the content in the templates. 

## Tasks

- [ ] Investigate best option to isolate upgrade related tasks (Tags, Flags.. etc)
- [ ] Create update protocol for each role.
- [ ] Testing.
- [ ] Update related configuration.

Greetings,
JP

**Comment by jonhattan** [comment]
FTR, I've created a PR that allows to override any template source, so users may perform customizations in their control repositories instead of directly in the servers -> https://github.com/wazuh/wazuh-ansible/pull/1337
