### ISSUE TITLE
Wazuh Ansible v4.0.3

### ISSUE THREAD

**Issue by neonmei** [wazuh/wazuh-ansible#512]
**Tasks overview**:

- [x] Bump components version
- [x] Validate configuration templates
- [x] Tests
- [x] Update changelog with summary of changes.
- [x] Update documentation to reflect new and deprecated settings.
- [x] Merge into release branch, and tag **v4.0.3**
- [x] Draft release

### Bump

Candidate versions to be included in this release (subject to change):

| Wazuh version | Elastic | ODFE   |
|---------------|---------|--------|
| v4.0.3        | 7.9.3   | 1.11.0 |

Like last's week release (#510), I'm proposing scheduling the elastic version `7.10` bump for a future release, in light of breaking changes. For details, see: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.10.html

**Comment by neonmei** [comment]
Local tests with verifiers branch ran succesfully.
Test run on Github Actions -> https://github.com/wazuh/wazuh-ansible/actions/runs/391973740

**Comment by neonmei** [comment]
Release is published -> https://github.com/wazuh/wazuh-ansible/releases/tag/v4.0.3
