### ISSUE TITLE
Wazuh Ansible v4.0.4

### ISSUE THREAD

**Issue by neonmei** [wazuh/wazuh-ansible#536]
**Tasks overview**:

- [x] Bump components version
- [ ] Validate configuration templates
- [x] Tests
- [x] Update changelog with summary of changes.
- [x] Update documentation to reflect new and deprecated settings.
- [x] Merge into release branch, and tag **v4.0.4**
- [X] Draft release

### Bump

Candidate versions to be included in this release (subject to change):

| Wazuh version | Elastic | ODFE   |
|---------------|---------|--------|
| v4.0.4        | 7.9.3   | 1.11.0 |

Similar to previous release (#512), the elastic version `7.10` bump is delayed for a future release.
