### ISSUE TITLE
[wazuh-ansible] Update v4.1.5 with Opendistro 1.13.2

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-ansible#593]
# Goal
According to our latest packages release, which only contains new Opendistro packages, we need to update the repository for using those packages.

# Tasks
- [x] Modify the repository to bump to 1.13.2 Opendistro version. Take into account the `kibana.yml` [modifications needed](https://github.com/wazuh/wazuh-documentation/blob/4.1/resources/open-distro/kibana/7.x/kibana_all_in_one.yml). 
- [x] Re-do v4.1.5 tag. 
- [x] Merge into `stable` branch. 

## Additional
- [x] Update to 1.13.2 `master`, `4.2` and `5.0-dev`
