### ISSUE TITLE
Change in Wazuh documentation Ansible

### ISSUE THREAD

**Issue by lastranikos** [wazuh/wazuh-ansible#638]
This change begins at the request of @santiago-bassett.

Change in Wazuh documentation:
- https://documentation.wazuh.com/current/deploying-with-ansible/guide/install-elk-server.html

Two issues were detected in the current documentation:
1. Outdated image:
    - https://documentation.wazuh.com/current/_images/ansible-elk1.png
2. Ansible's guide to the dashboard installation process. Use Elastichsearch. It should guide you in using OpenDistro.
 
Tasks to perform:
- [x] Repo Wazuh-Documentation
  - [x] PR of documentation with the necessary changes.
- [x] Repo Wazuh-Ansible
  - [x] Validate the deployment with Wazuh Ansible with OpenDistro
  - [x] Fix Opendistro deployment issues.

**Comment by lastranikos** [comment]
**Error: Add openjdk repository**
```
TASK [../roles/opendistro/opendistro-elasticsearch : Add openjdk repository] *****************************
fatal: [poc-allinone-wm]: FAILED! => {"changed": false, "msg": "apt cache update failed"}
```
Host information: Ubuntu 20.04.
It was not necessary to add this repo. I will see to put a conditional so that this task does not run in this distro and version.

**Error: Add Opendistro repository**
```
TASK [../roles/opendistro/opendistro-elasticsearch : Add Opendistro repository] **************************
fatal: [poc-allinone-wm]: FAILED! => {"changed": false, "msg": "apt cache update failed"}
```
Host information: Ubuntu 20.04.
This error occurred when trying to install the prerelease version of 4.2.3. Using the latest stable version 4.2.2 is not present. I will consult this to have better information on how to proceed.


**Error: Download Filebeat module packag**
```
TASK [../roles/wazuh/ansible-filebeat-oss : Download Filebeat module package] ****************************
fatal: [poc-allinone-wm]: FAILED! => {"changed": false, "dest": "/tmp/", "elapsed": 6, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/filebeat/wazuh-filebeat-0.1.tar.gz"}
```
Host information: Ubuntu 20.04.
This error occurred when trying to install the prerelease version of 4.2.3. Using the latest stable version 4.2.2 is not present. I will consult this to have better information on how to proceed.

**Error: Remove performance analyzer plugin from elasticsearch**
```
TASK [../roles/opendistro/opendistro-elasticsearch : Remove performance analyzer plugin from elasticsearch] ***
fatal: [poc-allinone-wm]: FAILED! => {"changed": true, "cmd": ["./elasticsearch-plugin", "remove", "opendistro-performance-analyzer"], "delta": "0:00:01.437514", "end": "2021-10-07 19:40:23.505763", "msg": "non-zero return code", "rc": 78, "start": "2021-10-07 19:40:22.068249", "stderr": "ERROR: plugin [opendistro-performance-analyzer] not found; run 'elasticsearch-plugin list' to get list of installed plugins", "stderr_lines": ["ERROR: plugin [opendistro-performance-analyzer] not found; run 'elasticsearch-plugin list' to get list of installed plugins"], "stdout": "-> removing [opendistro-performance-analyzer]...", "stdout_lines": ["-> removing [opendistro-performance-analyzer]..."]}
```
Host information: Ubuntu 20.04.
I already have the code that fixes this.

**TODO:**
- Create PR with fixes on the Ansible repo.
- Create PR with the change of Elasticsearch by Opendistro. In the installation routine with Ansible from the Wazuh documentation.

**Comment by lastranikos** [comment]
Start testing on Centos 8. @teddytpc1 @okynos

**Comment by lastranikos** [comment]
@okynos @teddytpc1 
This documentation PR, should be the last in the series that closes this issue.
https://github.com/wazuh/wazuh-documentation/pull/4462

**Comment by lastranikos** [comment]
@okynos @teddytpc1
This documentation PR, should be the last in the series that closes this issue.
wazuh/wazuh-documentation#4462

**Comment by colans** [comment]
I just pushed an MR to better handle the error checking when the Elasticsearch performance analyzer plugin is removed.  I also found a way to better determine when the task has actually changed anything.  Currently, this isn't handled at all, and gets incorrectly reported in Ansible statistics.  See #649 for details.

**Comment by lastranikos** [comment]
Talk to Sandra: and she asked me to add a fix. With the changes corresponding to redirects in: redirects.js within the PR

> Sandra: veo que has eliminado archivos y agregado nuevos, en ese caso hay que modificar redirects.js y agregar que URL son nuevos y cuales se han elimininado, y si es necesario alguna redireccion, por ejemplo si estoy en 4.1 viendo la instalacion de ELK y voy a 4.2 me lleve a la página de Open Distro

**Comment by lastranikos** [comment]
wazuh/wazuh-documentation#4462
 - Fix nomenclatures, redirections and nomenclatures notes.
 - Fix urls.
 - Merge branch '4.2' into 638-opendistro-deployment-for-4.2
