### ISSUE TITLE
System tests: Automatic Provision - Custom playbooks creation

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-ansible#785]
| Related Issue |
| --- | 
| https://github.com/wazuh/wazuh-jenkins/issues/3453 |

| Development branch |
| --- | 
| `poc-qa-provisioning-tool` |

### Description

According to  https://github.com/wazuh/wazuh-jenkins/issues/3453, it is necessary to create custom playbooks to provision different Wazuh environments. The current repository provides multiple playbooks for Wazuh environment provision. However, these are not versatile enough to support every kind of infrastructure.

### ToDo
- [x] Research current supported environments
- [x] Playbooks creation
   -  [x] Wazuh manager without filebeat
- [x] Edit playbooks to avoid ask for connection password

**Comment by Rebits** [comment]
@roronoasins / @Rebits 

### Manager only playbook
```
---
- hosts: managers
  become: true
  roles:
    - role: ../roles/wazuh/ansible-wazuh-manager
```
### Agent playbook

```
---
- hosts: agents
  become: yes
  become_user: root
  roles:
    - ../roles/wazuh/ansible-wazuh-agent
  vars:
    wazuh_managers:
      - address: "{{ manager_ip }}"
        port: 1514
        protocol: tcp
        api_port: 55000
        api_proto: 'http'
        api_user: ansible
        max_retries: 5
        retry_interval: 5
```

**Comment by fedepacher** [comment]
@fedepacher 

### Wazuh-indexer playbook

```
---
- hosts: wi_cluster
  become: true
  roles:
    - role: ../roles/wazuh/wazuh-indexer

  vars:
    instances:           # A certificate will be generated for every node using the name as CN.
      node1:
        name: node-1
        ip: "{{ hostvars.wi1.private_ip }}"
        role: indexer
      node2:
        name: node-2
        ip: "{{ hostvars.wi2.private_ip }}"
        role: indexer
      node3:
        name: node-3
        ip: "{{ hostvars.wi3.private_ip }}"
        role: indexer
```

### Wazuh-dashboard

```
---
- hosts: dashboard
  become: true
  roles:
    - role: ../roles/wazuh/wazuh-dashboard
```

### Filebeat playbook

```
---
- hosts: filebeat
  become: true
  roles:
    - role: ../roles/wazuh/ansible-filebeat-oss
```

**Comment by Rebits** [comment]
Playbooks specified in [comment](https://github.com/wazuh/wazuh-ansible/issues/785#issuecomment-1144785120), do not fit correctly the issue requirements. After some testing, we have achieved to provision every role using a single playbook, dependent on the wazuh-ansible roles.

### Wazuh testing environment playbook
```
---
# Certificates generation
    - hosts: wi1
      roles:
        - role: ../../roles/wazuh/wazuh-indexer
          indexer_network_host: "{{ private_ip }}"
          perform_installation: false
      become: true
      vars:
        indexer_node_master: true
      tags:
        - generate-certs

# Wazuh indexer cluster
    - hosts: wi_cluster
      strategy: free
      roles:
        - role: ../../roles/wazuh/wazuh-indexer
          indexer_network_host: "{{ private_ip }}"
      become: true
      become_user: root
      vars:
        indexer_node_master: true


    - hosts: manager
      roles:
        - role: "../../roles/wazuh/ansible-wazuh-manager"
      become: true
      become_user: root

    - hosts: filebeat
      roles:
        - role: "../../roles/wazuh/ansible-filebeat-oss"
      become: true
      become_user: root

# Indexer + dashboard node
    - hosts: dashboard
      roles:
        - role: "../../roles/wazuh/wazuh-indexer"
        - role: "../../roles/wazuh/wazuh-dashboard"
      become: true
      become_user: root
      vars:
        indexer_network_host: "{{ hostvars.dashboard.private_ip }}"
        indexer_node_master: false
        indexer_node_ingest: false
        indexer_node_data: false
        indexer_cluster_nodes: "{{ indexer_discovery_nodes }}"
        ansible_shell_allow_world_readable_temp: true
        wazuh_api_credentials:
          - id: default
            url: https://{{ hostvars.master.private_ip }}
            port: 55000
            username: wazuh
            password: wazuh

  # Agent
    - hosts: agent
      strategy: free
      become: yes
      become_user: root
      roles:
        - ../../roles/wazuh/ansible-wazuh-agent
```

**Comment by Rebits** [comment]
Maintaining wazuh-ansible branches for qa would be unfeasible due to the number of branches to maintain.
Therefore the approach to follow will be to create the playbooks in the wazuh-qa repository and use in our provisioning tool the wazuh-ansible roles.

For this reason, I move this issue to wazuh-qa.

**Comment by Rebits** [comment]
Issue moved to [wazuh/wazuh-qa #2985](https://github.com/wazuh/wazuh-qa/issues/2985) via [**ZenHub**](https://www.zenhub.com/)
