### ISSUE TITLE
Extend wazuh-ansible systems support for the Provisioning Tool

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh-ansible#797]
# Description
As we were working in instances [Deployer](https://github.com/wazuh/wazuh-qa/issues/2788) in Jenkins, now we need to provision those instances via our [Provisioning Tool](https://github.com/wazuh/wazuh-qa/issues/2796).

We have decided to use the `wazuh-ansible` playbooks to be able to install the Wazuh product and its necessary components.

# Tasks
- [x] Research wazuh-ansible plabooks 
- [x] Extend playbooks to add new systems support
  - [x] https://github.com/wazuh/wazuh-ansible/issues/798
  - [x] https://github.com/wazuh/wazuh-ansible/issues/799
  - [x] https://github.com/wazuh/wazuh-ansible/issues/800
