### ISSUE TITLE
Fix `AIO-Ubuntu-Single-Instance` test

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-ansible#909]
## Description

The `AIO-Ubuntu-Single-Instance` test is failing here: #903.
It should be analyzed and fixed.

## Tasks
- [ ] Analyze the cause of the issue.
- [ ] Fix the error.

## Validation
- [ ] The test should succeed.
