### ISSUE TITLE
Ansible installation fails on CentOS 8

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh-ansible#967]
### Description
As mentioned in this [comment](https://github.com/wazuh/wazuh/issues/18062#issuecomment-1653425278) the Ansible installation steps provided in the [documentation](https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/guide/install-ansible.html#installation-on-centos-rhel-fedora) fails on CentOS 8.

### Tasks
- [x] Reproduce the error on CentOS 8
- [x] Check if this happens on CentOS 7
- [ ] Provide a fix for the issue
- [ ] Update the documentation with the required changes

**Comment by davidcr01** [comment]
# Update Report

## Reproducing the error

An alternative to fix the error is to install `pipx` as the [Ansible official documentation](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#pipx-install) suggests

```console
[root@centos8 vagrant]# python3 -m pip install --user pipx
Collecting pipx
  Downloading pipx-1.0.0-py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 2.1 MB/s            
Collecting importlib-metadata>=3.3.0
  Downloading importlib_metadata-4.8.3-py3-none-any.whl (17 kB)
Collecting argcomplete>=1.9.4
  Downloading argcomplete-3.1.1-py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 1.5 MB/s             
Collecting userpath>=1.6.0
  Downloading userpath-1.7.0-py2.py3-none-any.whl (14 kB)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.6/site-packages (from pipx) (21.3)
Collecting zipp>=0.5
  Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.6/site-packages (from importlib-metadata>=3.3.0->pipx) (4.1.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.6/site-packages (from packaging>=20.0->pipx) (3.1.1)
Collecting click
  Downloading click-8.0.4-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 2.8 MB/s            
Installing collected packages: zipp, importlib-metadata, click, userpath, argcomplete, pipx
  WARNING: The script userpath is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pipx is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed argcomplete-3.1.1 click-8.0.4 importlib-metadata-4.8.3 pipx-1.0.0 userpath-1.7.0 zipp-3.6.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[root@centos8 vagrant]# python3 -m pipx ensurepath
Success! Added /root/.local/bin to the PATH environment variable.

Consider adding shell completions for pipx. Run 'pipx completions' for instructions.

You will need to open a new terminal or re-login for the PATH changes to take effect.

Otherwise pipx is ready to go! :sparkles: :star2: :sparkles:
[root@centos8 vagrant]# exit
exit
[vagrant@centos8 ~]$ sudo su


[root@centos8 vagrant]# pipx install --include-deps ansible
  installed package ansible 4.10.0, installed using Python 3.6.8
  These apps are now globally available
    - ansible
    - ansible-config
    - ansible-connection
    - ansible-console
    - ansible-doc
    - ansible-galaxy
    - ansible-inventory
    - ansible-playbook
    - ansible-pull
    - ansible-test
    - ansible-vault
done! :sparkles: :star2: :sparkles:

[root@centos8 vagrant]# ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current
 version: 3.6.8 (default, Sep 10 2021, 09:13:53) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]. This feature will be removed
 from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
/root/.local/pipx/venvs/ansible/lib64/python3.6/site-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.exceptions import InvalidSignature
ansible [core 2.11.12] 
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/pipx/venvs/ansible/lib64/python3.6/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible
  python version = 3.6.8 (default, Sep 10 2021, 09:13:53) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
```

**Comment by teddytpc1** [comment]
@davidcr01 I would go for the `Install Ansible using pip3` option.

**Comment by davidcr01** [comment]
The note in the documentation has been added: https://github.com/wazuh/wazuh-documentation/pull/6341
