### ISSUE TITLE
Support new stage RC 1 for 4.5.0 in wazuh-ansible repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-ansible#971]
## Description

This issue attempts to support a new stage RC 1 for 4.5.0 in the wazuh-ansible repository.

## Tasks

- [x] Ensure changelog is updated for 4.5.0
- [x] Create tag v4.5.0-rc1 from branch 4.5.0 on wazuh-ansible repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-ansible/releases/tag/v4.5.0-rc1
