### ISSUE TITLE
Support new stage RC 1 for 4.5.1 in wazuh-ansible repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-ansible#988]
## Description

This issue attempts to support a new stage RC 1 for 4.5.1 in the wazuh-ansible repository.

## Tasks

- [ ] Ensure changelog is updated for 4.5.1
- [ ] Create tag v4.5.1-rc1 from branch 4.5.1 on wazuh-ansible repository.
- [ ] Create a pre-release: https://github.com/wazuh/wazuh-ansible/releases/tag/v4.5.1-rc1
