### ISSUE TITLE
Change the MD5 checksums packages

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh-ansible#990]
# Description

As reported in https://github.com/wazuh/wazuh-ansible/issues/976, is necessary to change the checksums of the Windows packages.

This mistake is done because of the release process:
- The tag of the release is created.
- Generate the related packages.
And then, we should get the MD5 checksums of the packages and modify them before creating the definitive tag. This should be considered in the Release protocol.

The aim of this issue is to provisionally fix the packages of v4.4.5 and v4.5.0

## Tasks

- [x] Create a branch from the specified tag.
- [x] Change the MD5 checksum packages, using the `md5sum` command for example.
- [x] Merge the changes.
- [x] Re-tag.
- [x] Merge 4.5.0 into 4.5
- [x] Merge 4.4.5 into 4.4

**Comment by davidcr01** [comment]
# Update Report

## 4.4.5

- From the `4.4` branch, I created the `4.4.5` branch.
- Obtained the MD5 checksum: 
```console
davidcr01:~/Descargas$ md5sum wazuh-agent-4.4.5-1.msi 
396833b72a865be4b693f18ee2e34cde  wazuh-agent-4.4.5-1.msi
```
- Changed checksum in `roles/wazuh/ansible-wazuh-agent/defaults/main.yml`

## 4.5.0

- From the `4.5` branch, I created the `4.5.0` branch.
- Obtained the MD5 checksum: 
```console
davidcr01:~/Descargas$ md5sum wazuh-agent-4.5.0-1.msi 
fd53c0afc26394ef5ce6a0922186de29  wazuh-agent-4.5.0-1.msi
```
- Changed checksum in `roles/wazuh/ansible-wazuh-agent/defaults/main.yml`

**Comment by teddytpc1** [comment]
We need to merge `4.4.5` into `4.4` and `4.5.0` into `4.5`. I added the items to the description.

**Comment by davidcr01** [comment]
Missing merges:
- https://github.com/wazuh/wazuh-ansible/pull/1000
- https://github.com/wazuh/wazuh-ansible/pull/999
