### ISSUE TITLE
Support new stage RC 2 for 4.5.1 in wazuh-ansible repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-ansible#993]
## Description

This issue attempts to support a new stage RC 2 for 4.5.1 in the wazuh-ansible repository.

## Tasks

- [x] Change revision to `40502`.
- [x] Ensure changelog is updated for 4.5.1
- [x] Change revision to `40503`. https://github.com/wazuh/wazuh-ansible/pull/997
- [x] Create tag v4.5.1-rc2 from branch 4.5.1 on wazuh-ansible repository.
- [x] Create a pre-release: https://github.com/wazuh/wazuh-ansible/releases/tag/v4.5.1-rc2

**Comment by teddytpc1** [comment]
Reviewed.

**Comment by davidcr01** [comment]
Changed revision and re-tagged.

**Comment by teddytpc1** [comment]
Reviewed.

**Comment by teddytpc1** [comment]
Reviewed.
